"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { createClient } from "../../lib/supabase/client";

type Media={id:string;title:string;description:string;media_url:string;media_type:string;access_mode:"public"|"ppv"|"members";price_cents:number;categories:string[];is_published:boolean;sort_order:number;created_at:string};
const categories=["Fußfetisch","Latex","Leder","Shibari","Rope","Bondage","Femdom","Maledom","Switch","Keuschhaltung","Worship","Sensory","Petplay","Roleplay","Audio","Video","Foto","Tutorials","Workshops"];
const eur=(c:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format((c||0)/100);

export default function CreatorMediaPublisher(){
 const input=useRef<HTMLInputElement>(null);const[items,setItems]=useState<Media[]>([]);const[file,setFile]=useState<File|null>(null);const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[access,setAccess]=useState<"public"|"ppv"|"members">("public");const[price,setPrice]=useState("9.99");const[selected,setSelected]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();const{data}=await s.rpc("get_my_creator_media");setItems((data||[]) as Media[])}
 function toggle(c:string){setSelected(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])}
 function choose(e:ChangeEvent<HTMLInputElement>){setFile(e.target.files?.[0]||null)}
 async function publish(){if(!file){setMsg("Bitte zuerst eine Medien-Datei auswählen.");return}setBusy(true);setMsg("");const s=createClient();const{data:a}=await s.auth.getUser();if(!a.user){setBusy(false);setMsg("Bitte neu anmelden.");return}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${a.user.id}/content/${crypto.randomUUID()}-${safe}`;const{error:up}=await s.storage.from("domina-site-media").upload(path,file,{contentType:file.type,upsert:false});if(up){setBusy(false);setMsg("Upload konnte nicht gespeichert werden: "+up.message);return}const{data:url}=s.storage.from("domina-site-media").getPublicUrl(path);const mediaType=file.type.startsWith("video/")?"video":file.type.startsWith("audio/")?"audio":file.type.startsWith("image/")?"image":"file";const{error}=await s.rpc("save_creator_media",{p_id:null,p_media_url:url.publicUrl,p_media_type:mediaType,p_title:title||file.name,p_description:description,p_access_mode:access,p_price_cents:access==="ppv"?Math.round((Number(price)||0)*100):0,p_categories:selected,p_is_published:true,p_sort_order:0});setBusy(false);if(error){setMsg(error.message);return}setFile(null);setTitle("");setDescription("");setSelected([]);if(input.current)input.current.value="";setMsg("Veröffentlicht. Die Datei erscheint jetzt auf deiner öffentlichen Creator-Seite.");await load()}
 return <section className="adminPanel creatorPublisher"><span className="eyebrow">CREATOR CONTENT</span><h2>Medien-Datei veröffentlichen</h2><p className="hint">Jede Datei bekommt ihre eigene Freigabe: kostenlos öffentlich, einzeln gegen Bezahlung oder exklusiv für deine Membership.</p><label>Datei<input ref={input} type="file" accept="image/*,video/*,audio/*" onChange={choose}/></label><label>Titel<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={file?.name||"Titel des Contents"}/></label><label>Beschreibung<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Freigabe<select value={access} onChange={e=>setAccess(e.target.value as any)}><option value="public">Öffentlich · kostenlos</option><option value="ppv">Pay-per-View · Preis pro Datei</option><option value="members">Nur auf meiner Seite · Membership</option></select></label>{access==="ppv"&&<label>Preis pro Datei in €<input type="number" min="0.50" step="0.50" value={price} onChange={e=>setPrice(e.target.value)}/></label>}<div className="categoryField"><strong>Kategorien</strong><div className="categoryPicker compact">{categories.map(c=><button type="button" key={c} className={selected.includes(c)?"selected":""} onClick={()=>toggle(c)}>{selected.includes(c)?"✓ ":"+ "}{c}</button>)}</div></div><button className="primary" disabled={busy} onClick={publish}>{busy?"Wird veröffentlicht …":"Datei veröffentlichen"}</button>{msg&&<p className="hint">{msg}</p>}<div className="creatorMediaInventory"><strong>Deine veröffentlichten Dateien</strong>{items.length===0?<p className="hint">Noch keine Medien veröffentlicht.</p>:items.map(m=><article key={m.id}><div><b>{m.title||"Ohne Titel"}</b><span>{m.access_mode==="public"?"Öffentlich":m.access_mode==="members"?"Membership":`PPV · ${eur(m.price_cents)}`} · {m.categories.join(" · ")||"ohne Kategorie"}</span></div><em>{m.is_published?"Online":"Entwurf"}</em></article>)}</div></section>;
}
