"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "../../lib/supabase/client";
import CreatorMediaPublisher from "./creator-media-publisher";
import "./store.css";

type FeedMode="for-you"|"all"|"favorites";
type Media={id:string;site_slug:string;creator_name:string;title:string;description:string;media_url:string|null;storage_bucket:string|null;storage_path:string|null;media_type:string;access_mode:"public"|"ppv"|"members";price_cents:number;categories:string[];can_access:boolean;purchase_status:string|null};
const categories=["Fußfetisch","Latex","Leder","Shibari","Rope","Bondage","Femdom","Maledom","Switch","Keuschhaltung","Worship","Sensory","Petplay","Roleplay","Content","Audio","Video","Foto","Tutorials","Workshops"];
const euro=(c:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format((c||0)/100);

export default function StorePage(){
 const[owner,setOwner]=useState(false),[items,setItems]=useState<Media[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const[category,setCategory]=useState("all"),[query,setQuery]=useState(""),[feedMode,setFeedMode]=useState<FeedMode>("for-you"),[interests,setInterests]=useState<string[]>([]),[favorites,setFavorites]=useState<string[]>([]),[showInterests,setShowInterests]=useState(false);
 useEffect(()=>{try{setInterests(JSON.parse(localStorage.getItem("hod-content-interests")||"[]"));setFavorites(JSON.parse(localStorage.getItem("hod-content-favorites")||"[]"))}catch{} void load()},[]);
 async function load(){setLoading(true);const s=createClient();const[{data:u},{data,error}]=await Promise.all([s.auth.getUser(),s.rpc("get_public_creator_media_feed_v2")]);if(u.user){const r=String(u.user.user_metadata?.role||"").toLowerCase();setOwner(["dom","domina","switch"].includes(r))}if(error){setMessage(error.message);setItems([])}else{const rows=(data||[]) as Media[];const hydrated=await Promise.all(rows.map(async m=>{if(m.can_access&&m.storage_bucket&&m.storage_path){const res=await fetch(`/api/creator-media/url?id=${encodeURIComponent(m.id)}`);const signed=await res.json();return{...m,media_url:res.ok?signed.url:null}}return m}));setItems(hydrated)}setLoading(false)}
 function toggleInterest(c:string){setInterests(v=>{const n=v.includes(c)?v.filter(x=>x!==c):[...v,c];localStorage.setItem("hod-content-interests",JSON.stringify(n));return n})}
 function toggleFavorite(id:string){setFavorites(v=>{const n=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem("hod-content-favorites",JSON.stringify(n));return n})}
 async function buy(m:Media){const s=createClient();const{data:u}=await s.auth.getUser();if(!u.user){location.href="/anmelden";return}const{error}=await s.rpc("request_creator_media_purchase",{p_media_id:m.id});setMessage(error?error.message:"Kauf vorgemerkt. Sobald die Zahlung bestätigt ist, wird der Content freigeschaltet.");await load()}
 const visible=useMemo(()=>items.filter(m=>{const hay=[m.creator_name,m.title,m.description,...(m.categories||[])].join(" ").toLowerCase();if(query&&!hay.includes(query.toLowerCase()))return false;if(category!=="all"&&!m.categories?.includes(category))return false;if(feedMode==="favorites"&&!favorites.includes(m.id))return false;if(feedMode==="for-you"&&interests.length>0&&!m.categories?.some(c=>interests.includes(c)))return false;return true}),[items,query,category,feedMode,favorites,interests]);
 return <main className="storePage">
  <header className="storeHero"><div><Link href="/">← Zurück ins House</Link><span className="eyebrow">HOUSE OF DOMS · CONTENT</span><h1>Content & Kinks</h1><p>Echter Content von Creatorn im House: kostenlos, als Einzelkauf oder exklusiv über eine Membership.</p></div>{owner&&<div className="storeRole"><a className="active" href="#creator-upload">CONTENT HOCHLADEN</a></div>}</header>
  <section className="feedTabs"><button className={feedMode==="for-you"?"active":""} onClick={()=>setFeedMode("for-you")}>Für dich</button><button className={feedMode==="all"?"active":""} onClick={()=>setFeedMode("all")}>Alles entdecken</button><button className={feedMode==="favorites"?"active":""} onClick={()=>setFeedMode("favorites")}>Favoriten</button><button className="interestButton" onClick={()=>setShowInterests(v=>!v)}>♡ Interessen {interests.length?`(${interests.length})`:"festlegen"}</button></section>
  {showInterests&&<section className="interestPanel"><div><span className="eyebrow">DEIN FEED</span><h2>Was interessiert dich?</h2><p>Deine Auswahl steuert den persönlichen Content-Feed.</p></div><div className="categoryPicker">{categories.map(c=><button key={c} className={interests.includes(c)?"selected":""} onClick={()=>toggleInterest(c)}>{interests.includes(c)?"✓ ":"+ "}{c}</button>)}</div></section>}
  <section className="storeToolbar"><input placeholder="Content, Kink oder Creator suchen …" value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Alle Kategorien</option>{categories.map(c=><option key={c}>{c}</option>)}</select></section>
  {message&&<div className="feedHint">{message}</div>}
  {loading?<div className="emptyFeed">Content wird geladen …</div>:<section className="productGrid">{visible.map(m=><article className="productCard" key={m.id}><div className="productVisual">{m.can_access&&m.media_url?(m.media_type==="image"?<img src={m.media_url} alt={m.title}/>:m.media_type==="video"?<video src={m.media_url} controls playsInline/>:<strong>{m.media_type.toUpperCase()}</strong>):<><strong>{m.access_mode==="members"?"MEMBERS ONLY":"PAY-PER-VIEW"}</strong><span>{m.access_mode==="ppv"?euro(m.price_cents):"Membership"}</span></>}<button className={`favHeart${favorites.includes(m.id)?" saved":""}`} onClick={()=>toggleFavorite(m.id)}>{favorites.includes(m.id)?"♥":"♡"}</button></div><div className="productBody"><small><Link href={`/d/${m.site_slug}`}>{m.creator_name}</Link> · {m.access_mode==="public"?"Öffentlich":m.access_mode==="members"?"Membership":"Einzelkauf"}</small><h2>{m.title||"Creator Content"}</h2><div className="contentTags">{m.categories?.map(c=><button key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><p>{m.description}</p><footer>{m.access_mode==="public"?<strong>Kostenlos</strong>:m.access_mode==="ppv"?<strong>{euro(m.price_cents)}</strong>:<strong>Membership</strong>}{!m.can_access&&m.access_mode==="ppv"&&<button disabled={m.purchase_status==="pending_payment"} onClick={()=>buy(m)}>{m.purchase_status==="pending_payment"?"Zahlung ausstehend":"Freischalten"}</button>}{!m.can_access&&m.access_mode==="members"&&<Link href={`/d/${m.site_slug}#membership`}>Membership ansehen</Link>}{m.can_access&&<Link href={`/d/${m.site_slug}#content`}>Beim Creator öffnen →</Link>}<Link href={`/melden?type=content&id=${encodeURIComponent(m.id)}`}>Melden</Link></footer></div></article>)}</section>}
  {!loading&&visible.length===0&&<div className="emptyFeed">Noch kein passender Content. Ändere deine Interessen oder entdecke alles.</div>}
  {owner&&<section id="creator-upload" className="ownerGrid"><CreatorMediaPublisher/></section>}
  <section className="storeNotice"><strong>Drei Freigaben pro Datei</strong><p>Creator entscheiden für jede Datei: kostenlos öffentlich, Pay-per-View mit eigenem Preis oder exklusiv für aktive Memberships.</p></section>
 </main>
}
