"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import "../role-info.css";

type Lang="de"|"en";
const de={
  kicker:"FÜR DOMINAS",
  title:"Dein House. Deine Regeln. Deine Verwaltung.",
  lead:"House of Doms ist nicht nur ein Profilverzeichnis, sondern deine zentrale Plattform für Sichtbarkeit, Buchungen, Mitglieder, Kommunikation, Inhalte und Verwaltung. Du entscheidest selbst, wie öffentlich du auftreten möchtest und welche Bereiche nur für angenommene Subs sichtbar sind.",
  introTitle:"Was House of Doms für dich übernimmt",
  intro:["Deine öffentliche Präsenz, buchbare Angebote und deine private House-Verwaltung greifen an einem Ort ineinander. Besucher können dich über Discover finden, deine freigegebenen Informationen ansehen und – je nach Angebot – eine Anfrage, Bewerbung, Session oder Mitgliedschaft starten.","Nach der Anmeldung arbeitest du in deinem eigenen House-Bereich. Dort verwaltest du Studiozeiten, Kalender, Bewerbungen, Mitglieder, Nachrichten, Aufgaben, Regeln, Medien, Abos und Finanzen. Öffentliche Inhalte und interne Verwaltung bleiben dabei klar voneinander getrennt."],
  features:[["Eigene House-Präsenz","Profil, Beschreibung, Regeln, Angebote, Medien und öffentliche Informationen an einem Ort. Du legst fest, was außen sichtbar ist und was erst nach Aufnahme freigeschaltet wird."],["Discover & Buchbarkeit","Über Discover können neue Interessenten dich finden. Du veröffentlichst verfügbare Studiozeiten, Sessions oder Angebote und entscheidest selbst, was direkt buchbar ist."],["Kalender & Studiozeiten","Verfügbarkeiten, Studio-Sessions und bestätigte Termine zentral planen. Termine lassen sich übersichtlich verwalten und für deine persönliche Kalendernutzung vorbereiten."],["Bewerbungen & Mitglieder","Neue Subs können sich bewerben oder Kontakt aufnehmen. Du prüfst Anfragen, entscheidest über Aufnahme und verwaltest angenommene Mitglieder getrennt von bloßen Interessenten."],["Nachrichten & private Kammer","Kommunikation bleibt innerhalb des House strukturiert. Private Nachrichten und geschützte Bereiche helfen dir, nicht zwischen mehreren externen Plattformen wechseln zu müssen."],["Aufgaben & Kontrolle","Aufgaben erstellen, Fristen setzen, Countdowns nutzen, Fortschritt nachvollziehen und Rückmeldungen organisieren – passend zu deiner eigenen Dynamik und deinen Regeln."],["Sub-Akten & Regeln","Mitgliederinformationen, Notizen, vereinbarte Regeln, Freigaben und relevante House-Daten strukturiert an einem Ort dokumentieren."],["Abos & digitale Angebote","Mitgliedschaften, wiederkehrende Angebote und exklusive Inhalte bereitstellen. Du bestimmst Preis, Inhalt und Zugangsmodell deiner Angebote."],["Finanzen & Kassenbuch","Umsätze aus Abos, Medien, Tribute und Sessions nachvollziehen, Plattformabgaben einsehen und Auszahlungen übersichtlich kontrollieren."],["Homepage & Branding","Optional eine eigene House-Homepage mit Branding, eigener Darstellung und zusätzlichen Marketingmöglichkeiten nutzen."],["Bewertungen & Verifizierung","Vertrauen durch Verifizierungsstatus, vollständiges Profil und Bewertungen aufbauen. So erkennen neue Interessenten schneller, dass dein Auftritt professionell gepflegt ist."],["Events & Warteliste","Veranstaltungen oder besondere Termine sichtbar machen und bei ausgebuchten Angeboten Interessenten auf einer Warteliste sammeln."]],
  flow:[["1. Präsenz aufbauen","Du richtest Profil, öffentliche Informationen, Medien, Regeln und Angebote ein. Damit entsteht dein sichtbarer Auftritt auf der Plattform."],["2. Verfügbarkeit festlegen","Du pflegst Studiozeiten, buchbare Sessions und Termine. Nur das, was du freigibst, wird öffentlich buchbar oder sichtbar."],["3. Anfragen & Subs verwalten","Bewerbungen und Anfragen landen bei dir. Du entscheidest, wen du annimmst und welche privaten Bereiche danach freigeschaltet werden."],["4. Beziehung organisieren","Nachrichten, Aufgaben, Regeln, Kalender, Sub-Akten und weitere House-Funktionen helfen dir, laufende Dynamiken strukturiert zu verwalten."],["5. Angebote monetarisieren","Abos, Medien, Tribute sowie Online- oder Studio-Sessions können über die Plattform angeboten werden. Umsätze und Abgaben bleiben nachvollziehbar."],["6. Auswerten & wachsen","Bewertungen, Verifizierung, Discover, Statistiken und optionales Homepage-Branding helfen dir dabei, deine Präsenz professionell auszubauen."]],
  privacyTitle:"Öffentlich sichtbar oder privat – du entscheidest",
  privacy:["Dein öffentliches Profil dient dazu, neue Interessenten zu informieren und Vertrauen aufzubauen. Interne Bereiche wie Mitgliederverwaltung, private Nachrichten, Aufgaben oder Sub-Akten sind davon getrennt.","So kannst du House of Doms gleichzeitig als Marketingfläche und als Arbeitsbereich nutzen, ohne interne House-Daten offen auf der Plattform zu zeigen."],
  fees:"Das Gebührenmodell ist transparent nach Umsatzart getrennt. Für Abonnements, Tribute, Medien, Online-Sessions und Studio-Sessions gelten unterschiedliche Plattformanteile. Zahlungsanbieter-Kosten werden zusätzlich von deiner Auszahlung abgezogen. Die vollständigen Konditionen kannst du jederzeit separat einsehen."
};
const en={
  kicker:"FOR DOMMES",
  title:"Your House. Your rules. Your command centre.",
  lead:"House of Doms is more than a profile directory. It is your central platform for visibility, bookings, members, communication, content and administration. You decide what is public and what only accepted subs can access.",
  introTitle:"What House of Doms brings together for you",
  intro:["Your public presence, bookable offers and private House administration work together in one place. Visitors can discover you, view the information you publish and – depending on your offers – start an enquiry, application, session or membership.","After signing in, you work inside your own House area where you manage studio availability, calendar, applications, members, messages, tasks, rules, media, memberships and finances. Public information and internal administration remain clearly separated."],
  features:[["Your House presence","Profile, description, rules, offers, media and public information in one place. You decide what is visible publicly and what is unlocked only after acceptance."],["Discover & booking","New prospects can find you through Discover. Publish studio availability, sessions or offers and decide what can be booked directly."],["Calendar & studio time","Plan availability, studio sessions and confirmed appointments centrally and keep your schedule organised."],["Applications & members","Subs can apply or make contact. Review requests, decide who joins and keep accepted members separate from prospects."],["Messages & private chamber","Keep communication structured inside your House instead of spreading it across multiple external platforms."],["Tasks & control","Create tasks, set deadlines, use countdowns, track progress and organise feedback according to your own dynamic and rules."],["Sub files & rules","Keep member information, notes, agreed rules, permissions and relevant House data organised in one place."],["Memberships & digital offers","Offer recurring memberships, exclusive content and other digital products. You control pricing, content and access."],["Finances & cashbook","Track revenue from memberships, media, tributes and sessions, see platform fees and monitor payouts."],["Homepage & branding","Optionally use your own House homepage with branding and additional marketing options."],["Reviews & verification","Build trust with verification, profile completeness and reviews so new prospects can recognise a professional presence."],["Events & waitlist","Publish special events or dates and collect interested users on a waitlist when an offer is full."]],
  flow:[["1. Build your presence","Set up profile, public information, media, rules and offers to create your public presence."],["2. Set availability","Maintain studio time, bookable sessions and appointments. Only what you publish becomes visible or bookable."],["3. Manage enquiries & subs","Applications and enquiries come to you. You decide who is accepted and which private areas are then unlocked."],["4. Organise the relationship","Messages, tasks, rules, calendar and sub files help you manage ongoing dynamics in one place."],["5. Monetise your offers","Memberships, media, tributes, online sessions and studio sessions can be offered through the platform with transparent tracking."],["6. Analyse & grow","Reviews, verification, Discover, statistics and optional homepage branding help you grow your professional presence."]],
  privacyTitle:"Public or private – you decide",
  privacy:["Your public profile is designed to inform new prospects and build trust. Internal areas such as member management, private messages, tasks and sub files remain separate.","This allows you to use House of Doms both as a marketing surface and as a working environment without exposing internal House data."],
  fees:"The fee model is separated transparently by revenue type. Memberships, tributes, media, online sessions and studio sessions have different platform shares. Payment-provider fees are additionally deducted from your payout. You can view the full conditions at any time."
};

export default function Page(){
  const[lang,setLang]=useState<Lang>("de");
  useEffect(()=>{const s=localStorage.getItem("house-language");setLang(s==="en"?"en":"de")},[]);
  const t=lang==="de"?de:en;
  return <main className="roleInfoPage">
    <header className="roleInfoTop"><Link href="/#roles" className="roleInfoBack">← {lang==="de"?"Zurück":"Back"}</Link><div className="roleInfoBrand"><img src="/door-emblem.svg" alt=""/><span>HOUSE OF DOMS</span></div><button onClick={()=>{const n=lang==="de"?"en":"de";setLang(n);localStorage.setItem("house-language",n)}}>{lang.toUpperCase()}</button></header>
    <section className="roleInfoHero"><span>{t.kicker}</span><h1>{t.title}</h1><p>{t.lead}</p></section>
    <section className="roleInfoText"><span>{lang==="de"?"DIE PLATTFORM":"THE PLATFORM"}</span><h2>{t.introTitle}</h2>{t.intro.map(p=><p key={p}>{p}</p>)}</section>
    <section className="roleInfoGrid">{t.features.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</section>
    <section className="roleInfoFlow"><span>{lang==="de"?"SO LÄUFT ES AB":"HOW IT WORKS"}</span><h2>{lang==="de"?"Von deinem Profil bis zur laufenden House-Verwaltung":"From profile to everyday House management"}</h2><div>{t.flow.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section>
    <section className="roleInfoText roleInfoTextAccent"><span>{lang==="de"?"SICHTBARKEIT & PRIVATSPHÄRE":"VISIBILITY & PRIVACY"}</span><h2>{t.privacyTitle}</h2>{t.privacy.map(p=><p key={p}>{p}</p>)}</section>
    <section className="roleInfoFees"><div><span>{lang==="de"?"ZAHLUNGEN & ABGABEN":"PAYMENTS & FEES"}</span><h2>{lang==="de"?"Transparent geregelt":"Clear and transparent"}</h2><p>{t.fees}</p></div><Link href="/gebuehrenmodell">{lang==="de"?"Gebührenmodell ansehen →":"View fee model →"}</Link></section>
    <section className="roleInfoCta"><p>{lang==="de"?"Du kannst dein House Schritt für Schritt aufbauen und zunächst mit den Bereichen starten, die du wirklich brauchst.":"Build your House step by step and start with the areas you actually need."}</p><Link href="/anmelden?rolle=domina">{lang==="de"?"ALS DOMINA STARTEN":"START AS DOMME"}</Link></section>
  </main>
}
