"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import "../role-info.css";

type Lang="de"|"en";
const de={kicker:"FÜR DOMINAS",title:"Dein House. Deine Regeln. Deine Verwaltung.",lead:"Hier siehst du auf einen Blick, was du als Domina mit House of Doms machen kannst – von deiner öffentlichen Präsenz bis zu Buchungen, Mitgliedern, Finanzen und deinem privaten Command Center.",features:[["Eigene House-Präsenz","Profil, Informationen, Angebote, Medien und deine öffentliche Darstellung an einem Ort."],["Discover & Buchbarkeit","Gefunden werden, Studiozeiten veröffentlichen und buchbare Sessions verwalten."],["Kalender & Studiozeiten","Verfügbarkeiten, Termine und Studio-Sessions planen und in deinen Kalender übernehmen."],["Nachrichten & private Kammer","Direkte Kommunikation mit Subs und strukturierte private Bereiche."],["Aufgaben & Kontrolle","Aufgaben erstellen, Fristen setzen, Fortschritt sehen und Rückmeldungen organisieren."],["Mitglieder & Sub-Akten","Mitglieder, Bewerbungen, Regeln, Notizen und relevante House-Informationen verwalten."],["Abos & digitale Angebote","Mitgliedschaften und wiederkehrende Angebote für deine Community bereitstellen."],["Finanzen & Kassenbuch","Umsätze, Sessions und Plattformaktivitäten übersichtlich nachvollziehen."],["Homepage & Branding","Optional eine eigene House-Homepage nutzen und deine Präsenz professionell ausbauen."],["Bewertungen & Verifizierung","Vertrauen durch Verifizierungsstatus, Profilqualität und Bewertungen aufbauen."]],flow:[["1. Profil aufbauen","Öffentliche Informationen, Medien, Regeln und Angebote einrichten."],["2. Verfügbarkeit festlegen","Studiozeiten und buchbare Sessions in deinem Kalender pflegen."],["3. Subs verwalten","Bewerbungen prüfen, Mitglieder aufnehmen und private Bereiche organisieren."],["4. Umsatz verwalten","Abos, Tribute, Medien und Sessions nachvollziehen und Abrechnungen einsehen."]],fees:"Das Gebührenmodell ist transparent getrennt nach Abos, Tribute, Medien, Online- und Studio-Sessions. Zahlungsanbieter-Kosten werden von deiner Auszahlung abgezogen."};
const en={kicker:"FOR DOMMES",title:"Your House. Your rules. Your command centre.",lead:"See everything House of Doms gives you as a Domme – from your public presence to bookings, members, finances and your private command centre.",features:[["Your House presence","Profile, information, offers, media and your public presentation in one place."],["Discover & booking","Be found, publish studio availability and manage bookable sessions."],["Calendar & studio time","Plan availability, appointments and studio sessions and sync them to your calendar."],["Messages & private chamber","Direct communication with subs and structured private areas."],["Tasks & control","Create tasks, set deadlines, track progress and organise feedback."],["Members & sub files","Manage members, applications, rules, notes and relevant House information."],["Subscriptions & offers","Provide memberships and recurring offers for your community."],["Finances & cashbook","Track revenue, sessions and platform activity in one place."],["Homepage & branding","Optionally use your own House homepage and build a professional presence."],["Reviews & verification","Build trust with verification, profile quality and reviews."]],flow:[["1. Build your profile","Set up public information, media, rules and offers."],["2. Set availability","Maintain studio time and bookable sessions in your calendar."],["3. Manage subs","Review applications, accept members and organise private spaces."],["4. Manage revenue","Track memberships, tributes, media and sessions and view settlements."]],fees:"The fee model clearly separates memberships, tributes, media, online and studio sessions. Payment-provider costs are deducted from your payout."};
export default function Page(){const[lang,setLang]=useState<Lang>("de");useEffect(()=>{const s=localStorage.getItem("house-language");setLang(s==="en"?"en":"de")},[]);const t=lang==="de"?de:en;return <main className="roleInfoPage"><header className="roleInfoTop"><Link href="/#roles" className="roleInfoBack">← {lang==="de"?"Zurück":"Back"}</Link><div className="roleInfoBrand"><img src="/door-emblem.svg" alt=""/><span>HOUSE OF DOMS</span></div><button onClick={()=>{const n=lang==="de"?"en":"de";setLang(n);localStorage.setItem("house-language",n)}}>{lang.toUpperCase()}</button></header><section className="roleInfoHero"><span>{t.kicker}</span><h1>{t.title}</h1><p>{t.lead}</p></section><section className="roleInfoGrid">{t.features.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</section><section className="roleInfoFlow"><span>{lang==="de"?"SO LÄUFT ES AB":"HOW IT WORKS"}</span><h2>{lang==="de"?"Von deinem Profil bis zur Auszahlung":"From profile to payout"}</h2><div>{t.flow.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section><section className="roleInfoFees"><div><span>{lang==="de"?"ZAHLUNGEN & ABGABEN":"PAYMENTS & FEES"}</span><h2>{lang==="de"?"Transparent geregelt":"Clear and transparent"}</h2><p>{t.fees}</p></div><Link href="/gebuehrenmodell">{lang==="de"?"Gebührenmodell ansehen →":"View fee model →"}</Link></section><section className="roleInfoCta"><Link href="/anmelden?rolle=domina">{lang==="de"?"ALS DOMINA STARTEN":"START AS DOMME"}</Link></section></main>}
