"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../lib/supabase/client";
import "./hub.css";

type Metric={sessions_requested:number;sessions_confirmed:number;media_count:number;active_members:number;followers:number;pending_sales:number};
type Item={kind:string;item_id:string;title:string;subtitle:string;status:string;href:string;event_at:string};
export default function HubPage(){
 const[role,setRole]=useState(""),[m,setM]=useState<Metric|null>(null),[items,setItems]=useState<Item[]>([]),[msg,setMsg]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();const{data:a}=await s.auth.getUser();if(!a.user){location.href="/anmelden?next=/hub";return}const{data:p}=await s.from("profiles").select("role").eq("id",a.user.id).maybeSingle();const r=String(p?.role||a.user.user_metadata?.role||"sub").toLowerCase();setRole(r);if(["dom","domina","switch"].includes(r)){const{data,error}=await s.rpc("get_creator_hub_metrics");if(error)setMsg(error.message);else setM((data||[])[0]||null)}else{const{data,error}=await s.rpc("get_member_hub");if(error)setMsg(error.message);else setItems((data||[]) as Item[])}}
 const creator=["dom","domina","switch"].includes(role);
 return <main className="hubPage"><header><Link href="/dashboard">← Dashboard</Link><span>HOUSE OF DOMS · {creator?"CREATOR":"MEMBER"} HUB</span><h1>{creator?"Dein Creator-Bereich.":"Alles, was du im House nutzt."}</h1><p>{creator?"Sessions, Content, Memberships, Community und Finanzen in einer Übersicht.":"Buchungen, Memberships und gekaufter Content an einem Ort."}</p></header>{msg&&<p className="hubMessage">{msg}</p>}
 {creator&&m&&<><section className="hubMetrics"><article><span>Neue Sessions</span><strong>{m.sessions_requested}</strong></article><article><span>Bestätigt</span><strong>{m.sessions_confirmed}</strong></article><article><span>Content</span><strong>{m.media_count}</strong></article><article><span>Members</span><strong>{m.active_members}</strong></article><article><span>Follower</span><strong>{m.followers}</strong></article><article><span>Offene Käufe</span><strong>{m.pending_sales}</strong></article></section><section className="hubGrid"><Link href="/sessions"><b>Sessions</b><span>Anfragen bestätigen, verschieben oder abschließen.</span></Link><Link href="/kalender"><b>Kalender</b><span>Verfügbarkeit und Studio-Zeitfenster verwalten.</span></Link><Link href="/store"><b>Content</b><span>Medien veröffentlichen und Freigaben steuern.</span></Link><Link href="/abonnements"><b>Memberships</b><span>Pakete, Benefits und Mitglieder verwalten.</span></Link><Link href="/kassenbuch"><b>Finanzen</b><span>Content, Memberships und Sessions zusammenführen.</span></Link><Link href="/kammer"><b>Nachrichten</b><span>Private Kontakte und Anfragen beantworten.</span></Link><Link href="/benachrichtigungen"><b>Benachrichtigungen</b><span>Neue Aktivitäten im House prüfen.</span></Link><Link href="/homepage-builder"><b>Creator-Seite</b><span>Öffentliche Präsenz gestalten und veröffentlichen.</span></Link></section></>}
 {!creator&&<section className="memberHub">{items.length===0?<p>Noch keine Buchungen, Käufe oder Memberships.</p>:items.map(x=><Link href={x.href} key={x.kind+x.item_id}><small>{x.kind.toUpperCase()} · {x.status}</small><b>{x.title}</b><span>{x.subtitle}</span></Link>)}<div className="hubGrid"><Link href="/discover"><b>Discover</b><span>Creator und Kinks entdecken.</span></Link><Link href="/store"><b>Mein Content</b><span>Freigeschalteten Content und Favoriten öffnen.</span></Link><Link href="/kalender"><b>Kalender</b><span>Sessions und Termine im Blick behalten.</span></Link><Link href="/benachrichtigungen"><b>Benachrichtigungen</b><span>Statusänderungen und neue Aktivitäten sehen.</span></Link></div></section>}</main>
}