"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import "../role-info.css";

type Lang="de"|"en";
const de={
  kicker:"FÜR SUBS / SKLAVEN",
  title:"Finde Führung, Struktur und dein passendes House.",
  lead:"House of Doms hilft dir dabei, Dominas zu entdecken, Angebote zu verstehen und nach einer Aufnahme alle wichtigen Bereiche deiner Verbindung an einem Ort zu nutzen. Statt viele einzelne Chats, Kalender und Notizen zu brauchen, findest du hier deine Termine, Aufgaben, Nachrichten und gebuchten Angebote gebündelt.",
  introTitle:"Was dich auf House of Doms erwartet",
  intro:["Du kannst zunächst öffentlich über Discover nach Dominas suchen, Profile vergleichen und sehen, welche Angebote oder Studiozeiten freigegeben wurden. Du musst dafür nicht sofort Mitglied eines House sein.","Wenn du eine passende Domina gefunden hast, kannst du – je nach ihrem Angebot – Kontakt aufnehmen, dich bewerben, eine Session buchen oder ein Abo abschließen. Nach einer Annahme wird dein privater Bereich wichtiger: Dort findest du nur die Inhalte und Funktionen, die für deine Verbindung mit dieser Domina vorgesehen sind."],
  features:[["Discover","Dominas durchsuchen, Profile vergleichen und herausfinden, welches House, welcher Stil und welche Angebote zu dir passen."],["Bewerben & beitreten","Kontakt aufnehmen, eine Bewerbung senden und nach Annahme einem House beitreten. Die Domina entscheidet selbst über die Aufnahme."],["Sessions buchen","Verfügbare Studiozeiten oder andere angebotene Sessions auswählen, Preis und Leistung ansehen und eine Buchung anfragen oder abschließen."],["Aufgaben & Countdown","Aktuelle Aufgaben, Fristen und Countdowns übersichtlich sehen, damit du weißt, was ansteht und bis wann etwas erledigt werden soll."],["Nachrichten","Private Kommunikation mit deiner Domina innerhalb des House statt verstreuter Chats auf mehreren Plattformen."],["Abonnements & Inhalte","Mitgliedschaften oder exklusive Angebote abonnieren und – je nach Freigabe – zusätzliche Inhalte oder Medien erhalten."],["Kalender","Gebuchte Sessions, Termine und House-Ereignisse an einem Ort verfolgen, damit du keine bestätigten Zeiten aus dem Blick verlierst."],["Regeln & Freigaben","Vereinbarte Regeln, Grenzen, Freigaben oder andere strukturierte House-Informationen dort sehen, wo sie für deine Verbindung vorgesehen sind."],["Keuschhaltung & spezielle Bereiche","Falls deine Domina entsprechende Funktionen nutzt, können vereinbarte Bereiche wie Keuschhaltung oder andere laufende Vereinbarungen dokumentiert werden."],["Favoriten & Bewertungen","Dominas merken, Profile vergleichen und Bewertungen als zusätzliche Orientierung bei der Auswahl nutzen."],["Events & Warteliste","Öffentliche oder freigegebene Veranstaltungen entdecken und dich bei ausgebuchten Angeboten auf eine Warteliste setzen lassen."],["Privater House-Bereich","Nach Aufnahme bekommst du keinen allgemeinen Zugang zu allem, sondern nur zu den Bereichen, die deine Domina für dich und ihre Mitglieder vorgesehen hat."]],
  flow:[["1. Entdecken","Über Discover siehst du Dominas, öffentliche Profile, Angebote und – wenn freigegeben – verfügbare Zeiten."],["2. Informieren","Lies Profil, Regeln, Beschreibung und Angebot genau durch. So kannst du besser einschätzen, ob Stil, Erwartungen und Rahmen zu dir passen."],["3. Bewerben oder buchen","Je nach Domina kannst du eine Bewerbung senden, Kontakt aufnehmen, eine Session wählen oder ein anderes Angebot nutzen."],["4. Aufnahme ins House","Wirst du angenommen, erhältst du Zugang zu deinem privaten Bereich. Dort werden die für dich relevanten House-Funktionen sichtbar."],["5. Verbindung verwalten","Aufgaben, Nachrichten, Regeln, Termine und weitere freigegebene Bereiche helfen dir, den Überblick über laufende Vereinbarungen zu behalten."],["6. Angebote nutzen","Abos, Medien, Tribute oder Sessions können direkt über die jeweils freigegebenen Angebote genutzt werden. Vor einer Zahlung siehst du immer Preis und Leistung."]],
  privacyTitle:"Nicht alles ist öffentlich – und das ist Absicht",
  privacy:["Öffentliche Profile und Discover helfen dir beim Kennenlernen und Vergleichen. Private Nachrichten, Aufgaben, Regeln und persönliche House-Bereiche sind davon getrennt.","Welche Funktionen du nach einer Aufnahme tatsächlich siehst, hängt von der jeweiligen Domina und ihrer House-Struktur ab. So bleibt die Plattform übersichtlich und du bekommst nur die Bereiche, die für deine Verbindung relevant sind."],
  payment:"Für dich zählt vor allem: Bevor du etwas buchst oder kaufst, siehst du, welches Angebot du auswählst und welchen Preis die Domina dafür festgelegt hat. Je nach Angebot können Abonnements, Medien, Tribute, Online-Sessions oder Studio-Sessions verfügbar sein. Plattformabgaben und Auszahlungsgebühren betreffen die Domina und gehören deshalb nicht in deinen Bereich."
};
const en={
  kicker:"FOR SUBS",
  title:"Find guidance, structure and the right House.",
  lead:"House of Doms helps you discover Dommes, understand their offers and, once accepted, use the important parts of your connection in one place. Instead of scattered chats, calendars and notes, you can keep appointments, tasks, messages and booked offers together.",
  introTitle:"What to expect on House of Doms",
  intro:["You can start by using Discover to browse Dommes, compare public profiles and see offers or studio availability that has been made public. You do not need to be a House member just to explore.","Once you find a Domme who fits, you may be able to contact her, apply, book a session or join a membership depending on what she offers. After acceptance, your private area becomes relevant and only the functions intended for your connection are shown there."],
  features:[["Discover","Browse Dommes, compare profiles and find the House, style and offers that fit you."],["Apply & join","Make contact, send an application and join a House after acceptance. The Domme decides who is admitted."],["Book sessions","Choose available studio time or other sessions, review price and service, and request or complete a booking."],["Tasks & countdown","See current tasks, deadlines and countdowns so you know what is due and when."],["Messages","Keep private communication with your Domme inside the House instead of across multiple external chats."],["Memberships & content","Join memberships or exclusive offers and access additional content or media when it is made available to you."],["Calendar","Track booked sessions, appointments and House events in one place so confirmed dates remain easy to find."],["Rules & permissions","View agreed rules, boundaries, permissions and other structured House information where it is relevant to your connection."],["Chastity & special areas","If your Domme uses these functions, agreed areas such as chastity or other ongoing arrangements can be documented."],["Favourites & reviews","Save Dommes, compare profiles and use reviews as an additional orientation when choosing."],["Events & waitlists","Discover public or available events and join a waitlist when an offer is full."],["Private House area","After acceptance you do not receive access to everything; you only see the areas your Domme has intended for you and her members."]],
  flow:[["1. Discover","Use Discover to view Dommes, public profiles, offers and available times that have been published."],["2. Learn more","Read profiles, rules, descriptions and offers carefully to see whether style, expectations and framework fit you."],["3. Apply or book","Depending on the Domme, send an application, make contact, choose a session or use another available offer."],["4. Join the House","If accepted, you gain access to your private area where the relevant House functions become visible."],["5. Manage the connection","Tasks, messages, rules, appointments and other released areas help you stay organised."],["6. Use offers","Memberships, media, tributes or sessions can be used through the offers made available to you. Price and service are shown before payment."]],
  privacyTitle:"Not everything is public – by design",
  privacy:["Public profiles and Discover help you explore and compare. Private messages, tasks, rules and personal House areas remain separate.","What you actually see after acceptance depends on the Domme and her House structure. This keeps the platform focused and shows you only the areas relevant to your connection."],
  payment:"For you, the important part is simple: before booking or buying anything, you can see the offer and the price set by the Domme. Depending on what is available, this may include memberships, media, tributes, online sessions or studio sessions. Platform commissions and payout fees apply to the Domme and therefore do not belong in your area."
};

export default function Page(){
  const[lang,setLang]=useState<Lang>("de");
  useEffect(()=>{const s=localStorage.getItem("house-language");setLang(s==="en"?"en":"de")},[]);
  const t=lang==="de"?de:en;
  return <main className="roleInfoPage">
    <header className="roleInfoTop"><Link href="/#roles" className="roleInfoBack">← {lang==="de"?"Zurück":"Back"}</Link><div className="roleInfoBrand"><img src="/door-emblem.svg" alt=""/><span>HOUSE OF DOMS</span></div><button onClick={()=>{const n=lang==="de"?"en":"de";setLang(n);localStorage.setItem("house-language",n)}}>{lang.toUpperCase()}</button></header>
    <section className="roleInfoHero"><span>{t.kicker}</span><h1>{t.title}</h1><p>{t.lead}</p></section>
    <section className="roleInfoText"><span>{lang==="de"?"DIE PLATTFORM":"THE PLATFORM"}</span><h2>{t.introTitle}</h2>{t.intro.map(p=><p key={p}>{p}</p>)}</section>
    <section className="roleInfoGrid">{t.features.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</section>
    <section className="roleInfoFlow"><span>{lang==="de"?"SO LÄUFT ES AB":"HOW IT WORKS"}</span><h2>{lang==="de"?"Vom ersten Entdecken bis in dein privates House":"From first discovery to your private House"}</h2><div>{t.flow.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section>
    <section className="roleInfoText roleInfoTextAccent"><span>{lang==="de"?"PRIVATSPHÄRE & STRUKTUR":"PRIVACY & STRUCTURE"}</span><h2>{t.privacyTitle}</h2>{t.privacy.map(p=><p key={p}>{p}</p>)}</section>
    <section className="roleInfoFees"><div><span>{lang==="de"?"ZAHLUNGEN":"PAYMENTS"}</span><h2>{lang==="de"?"Klar, bevor du zahlst":"Clear before you pay"}</h2><p>{t.payment}</p></div></section>
    <section className="roleInfoCta"><p>{lang==="de"?"Du kannst zuerst in Ruhe entdecken und dich erst dann anmelden, wenn du eine Domina oder ein Angebot gefunden hast, das zu dir passt.":"Explore first and sign up when you find a Domme or offer that fits you."}</p><Link href="/anmelden?rolle=sub">{lang==="de"?"ALS SUB BEITRETEN":"JOIN AS SUB"}</Link></section>
  </main>
}
