"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import "../role-info.css";

type Lang="de"|"en";
const de={kicker:"FÜR SUBS / SKLAVEN",title:"Finde Führung, Struktur und dein passendes House.",lead:"Hier siehst du, was du als Sub oder Sklave auf House of Doms machen kannst – vom Entdecken einer Domina bis zu Bewerbungen, Aufgaben, Sessions, Abos und deinem privaten Bereich.",features:[["Discover","Dominas durchsuchen, Profile vergleichen und herausfinden, welches House zu dir passt."],["Bewerben & beitreten","Kontakt aufnehmen, Bewerbungen senden und nach Annahme dem House beitreten."],["Aufgaben & Countdown","Aktuelle Aufgaben sehen – inklusive großem Countdown bis zur nächsten Aufgabe."],["Nachrichten","Private Kommunikation innerhalb des House statt verstreuter Chats auf verschiedenen Plattformen."],["Sessions buchen","Verfügbare Studiozeiten und Sessions auswählen und buchen."],["Abonnements","Mitgliedschaften und exklusive Angebote deiner Domina abonnieren."],["Kalender","Gebuchte Sessions, Termine und House-Ereignisse übersichtlich verfolgen."],["Keuschhaltung & Regeln","Vereinbarte Bereiche wie Keuschhaltung, Regeln und Freigaben strukturiert dokumentieren."],["Favoriten & Bewertungen","Dominas merken, Profile vergleichen und Bewertungen als Orientierung nutzen."],["Events & Warteliste","Veranstaltungen entdecken und dich bei ausgebuchten Angeboten auf Wartelisten setzen."]],flow:[["1. Entdecken","Über Discover Dominas, Angebote und verfügbare Zeiten ansehen."],["2. Bewerben oder buchen","Kontakt aufnehmen, Bewerbung senden oder eine angebotene Session auswählen."],["3. Private Verbindung nutzen","Nach Aufnahme Aufgaben, Nachrichten, Regeln und Termine im persönlichen Bereich sehen."],["4. Bezahlen & verwalten","Abos, Medien, Tribute oder Sessions transparent über die Plattform nutzen."]],fees:"Vor einer Zahlung siehst du Preis und Leistung klar. Je nach Angebot können Abos, Tribute, Medien, Online-Sessions oder Studio-Sessions genutzt werden."};
const en={kicker:"FOR SUBS",title:"Find guidance, structure and the right House.",lead:"See what you can do as a sub on House of Doms – from discovering a Domme to applications, tasks, sessions, memberships and your private area.",features:[["Discover","Browse Dommes, compare profiles and find the House that fits you."],["Apply & join","Make contact, send an application and join the House after acceptance."],["Tasks & countdown","See current tasks including a large countdown to the next task."],["Messages","Private communication inside the House instead of scattered external chats."],["Book sessions","Choose and book available studio times and sessions."],["Subscriptions","Subscribe to memberships and exclusive offers from your Domme."],["Calendar","Keep booked sessions, appointments and House events organised."],["Chastity & rules","Document agreed areas such as chastity, rules and permissions in a structured way."],["Favourites & reviews","Save Dommes, compare profiles and use reviews for orientation."],["Events & waitlists","Discover events and join waitlists when an offer is full."]],flow:[["1. Discover","Browse Dommes, offers and available times through Discover."],["2. Apply or book","Make contact, send an application or select an offered session."],["3. Use your private connection","After joining, see tasks, messages, rules and appointments in your personal area."],["4. Pay & manage","Use memberships, media, tributes or sessions transparently through the platform."]],fees:"Before paying you see the price and service clearly. Depending on the offer, memberships, tributes, media, online sessions or studio sessions can be used."};
export default function Page(){const[lang,setLang]=useState<Lang>("de");useEffect(()=>{const s=localStorage.getItem("house-language");setLang(s==="en"?"en":"de")},[]);const t=lang==="de"?de:en;return <main className="roleInfoPage"><header className="roleInfoTop"><Link href="/#roles" className="roleInfoBack">← {lang==="de"?"Zurück":"Back"}</Link><div className="roleInfoBrand"><img src="/door-emblem.svg" alt=""/><span>HOUSE OF DOMS</span></div><button onClick={()=>{const n=lang==="de"?"en":"de";setLang(n);localStorage.setItem("house-language",n)}}>{lang.toUpperCase()}</button></header><section className="roleInfoHero"><span>{t.kicker}</span><h1>{t.title}</h1><p>{t.lead}</p></section><section className="roleInfoGrid">{t.features.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</section><section className="roleInfoFlow"><span>{lang==="de"?"SO LÄUFT ES AB":"HOW IT WORKS"}</span><h2>{lang==="de"?"Vom Entdecken bis ins private House":"From discovery to your private House"}</h2><div>{t.flow.map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section><section className="roleInfoFees"><div><span>{lang==="de"?"ZAHLUNGEN":"PAYMENTS"}</span><h2>{lang==="de"?"Klar, bevor du zahlst":"Clear before you pay"}</h2><p>{t.fees}</p></div><Link href="/gebuehrenmodell">{lang==="de"?"Gebührenmodell ansehen →":"View fee model →"}</Link></section><section className="roleInfoCta"><Link href="/anmelden?rolle=sub">{lang==="de"?"ALS SUB BEITRETEN":"JOIN AS SUB"}</Link></section></main>}
