"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "../../../lib/supabase/client";
import "./templates.css";

type Template={id:string;title:string;description:string;required_proof_types:string[];priority:string;points:number;default_release_delay_minutes:number;default_due_after_minutes:number|null;recurrence_rule:string|null};
type Candidate={user_id:string;display_name:string;role:string};

export default function TaskTemplatesPage(){
 const [templates,setTemplates]=useState<Template[]>([]),[people,setPeople]=useState<Candidate[]>([]),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[priority,setPriority]=useState("normal"),[points,setPoints]=useState(0),[proof,setProof]=useState<string[]>(["text"]),[dueMinutes,setDueMinutes]=useState(1440),[rule,setRule]=useState("none");
 const [selectedTemplate,setSelectedTemplate]=useState(""),[assigned,setAssigned]=useState(""),[start,setStart]=useState(()=>new Date(Date.now()+3600000).toISOString().slice(0,16)),[count,setCount]=useState(1),[interval,setInterval]=useState("weekly"),[saving,setSaving]=useState(false);
 async function load(){const s=createClient();const [{data:t,error:te},{data:p}]=await Promise.all([s.from("task_templates").select("*").order("created_at",{ascending:false}),s.rpc("get_house_task_candidates")]);if(te)setMsg(te.message);setTemplates((t||[]) as Template[]);setPeople((p||[]) as Candidate[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 const selected=useMemo(()=>templates.find(t=>t.id===selectedTemplate)||null,[templates,selectedTemplate]);
 function toggle(v:string){setProof(cur=>cur.includes(v)?cur.filter(x=>x!==v):[...cur,v])}
 async function saveTemplate(e:FormEvent){e.preventDefault();if(!title.trim())return;setSaving(true);setMsg("");const s=createClient();const {error}=await s.rpc("save_task_template",{p_title:title,p_description:description,p_required_proof_types:proof,p_priority:priority,p_points:points,p_release_delay_minutes:0,p_due_after_minutes:dueMinutes||null,p_recurrence_rule:rule==="none"?null:rule});setSaving(false);if(error){setMsg(error.message);return}setTitle("");setDescription("");setMsg("Vorlage gespeichert.");await load()}
 function addInterval(base:Date,i:number){const d=new Date(base);if(interval==="daily")d.setDate(d.getDate()+i);else if(interval==="monthly")d.setMonth(d.getMonth()+i);else d.setDate(d.getDate()+7*i);return d}
 async function createSeries(e:FormEvent){e.preventDefault();if(!selectedTemplate||!assigned)return;setSaving(true);setMsg("");const s=createClient();const base=new Date(start);let made=0;for(let i=0;i<Math.max(1,Math.min(count,52));i++){const release=addInterval(base,i);const {error}=await s.rpc("create_task_from_template",{p_template_id:selectedTemplate,p_assigned_to:assigned,p_release_at:release.toISOString()});if(error){setMsg(`Nach ${made} Aufgaben gestoppt: ${error.message}`);setSaving(false);return}made++}setSaving(false);setMsg(`${made} Aufgabe${made===1?"":"n"} geplant.`)}
 return <main className="templatePage"><header><div><Link href="/aufgaben">← Aufgaben</Link><span>DOM / DOMINA · AUTOMATION</span><h1>Aufgaben-Vorlagen</h1><p>Einmal definieren, danach einzelne Aufgaben oder komplette Serien mit Freigabezeit erzeugen.</p></div></header>{msg&&<p className="templateMsg">{msg}</p>}
 <section className="templateLayout"><form className="templatePanel" onSubmit={saveTemplate}><span className="eyebrow">NEUE VORLAGE</span><h2>Baustein erstellen</h2><label>Titel<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Beschreibung<textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="row"><label>Priorität<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Niedrig</option><option value="normal">Normal</option><option value="high">Hoch</option><option value="critical">Kritisch</option></select></label><label>Punkte<input type="number" min={0} value={points} onChange={e=>setPoints(Number(e.target.value)||0)}/></label><label>Fällig nach Minuten<input type="number" min={1} value={dueMinutes} onChange={e=>setDueMinutes(Number(e.target.value)||0)}/></label></div><div className="proof"><span>Nachweis</span>{["text","image","video"].map(v=><button type="button" key={v} className={proof.includes(v)?"active":""} onClick={()=>toggle(v)}>{v==="text"?"Text":v==="image"?"Bild":"Video"}</button>)}</div><label>Empfohlene Serie<select value={rule} onChange={e=>setRule(e.target.value)}><option value="none">Keine</option><option value="daily">Täglich</option><option value="weekly">Wöchentlich</option><option value="monthly">Monatlich</option></select></label><button className="primary" disabled={saving}>{saving?"Speichert …":"Vorlage speichern"}</button></form>
 <div className="templatePanel"><span className="eyebrow">VORLAGEN</span><h2>{loading?"Lädt …":`${templates.length} gespeichert`}</h2><div className="templateList">{templates.map(t=><button type="button" key={t.id} className={selectedTemplate===t.id?"selected":""} onClick={()=>{setSelectedTemplate(t.id);if(t.recurrence_rule)setInterval(t.recurrence_rule)}}><div><strong>{t.title}</strong><span>{t.priority.toUpperCase()} · {t.points} Punkte · {t.required_proof_types.join(" + ")}</span></div><b>→</b></button>)}</div></div>
 <form className="templatePanel seriesPanel" onSubmit={createSeries}><span className="eyebrow">SERIE PLANEN</span><h2>{selected?.title||"Vorlage wählen"}</h2><label>Sub/Sklave<select value={assigned} onChange={e=>setAssigned(e.target.value)} required><option value="">Auswählen …</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name}</option>)}</select></label><label>Erste Freigabe<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><div className="row"><label>Wiederholungen<input type="number" min={1} max={52} value={count} onChange={e=>setCount(Number(e.target.value)||1)}/></label><label>Rhythmus<select value={interval} onChange={e=>setInterval(e.target.value)}><option value="daily">Täglich</option><option value="weekly">Wöchentlich</option><option value="monthly">Monatlich</option></select></label></div><p className="hint">Jede Wiederholung wird als eigene Aufgabe mit eigener Freigabe erzeugt. Der Sub sieht den Inhalt erst zum jeweiligen Zeitpunkt.</p><button className="primary" disabled={saving||!selectedTemplate}>{saving?"Plant …":"Serie erstellen"}</button></form></section></main>
}
