"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState, type CSSProperties } from "react";
import "./entrance-reference.css";
import "./entrance-jpg-fix.css";
import "./landing-marketing.css";
import "./role-selector.css";

type Lang = "de" | "en";
type Audience = "creator" | "member" | null;

const copy = {
  de: {
    nav:{discover:"ENTDECKEN",creator:"FÜR CREATOR",member:"FÜR MEMBERS",how:"SO FUNKTIONIERT'S",pay:"ZAHLUNGEN",login:"LOGIN"},
    enter:"House betreten",
    flyingWords:["KINK","FETISCH","SHIBARI","ROPE","LATEX","LEDER","BONDAGE","FÜSSE","DOMINANZ","HINGABE","SWITCH","WORSHIP","KEUSCHHEIT","ROLEPLAY","SENSORY","PETPLAY","VERTRAUEN","KONSENS"],
    intro:{kicker:"HOUSE OF DOMS",title:"Ein House für Kink, Fetisch, Content und Sessions.",lead:"House of Doms ist nicht nur für Dominas und Subs. Hier finden Creator, Session-Anbieter, Rigger, Fetisch-Liebhaber, Switches und neugierige Members einen gemeinsamen Ort zum Entdecken, Verkaufen, Buchen, Kommunizieren und Organisieren."},
    why:[["Kinks entdecken","Profile, Content und Sessions nach Interessen wie Shibari, Latex, Bondage, Fußfetisch, D/s und vielen weiteren Kinks entdecken."],["Content & Sessions","Fotos, Videos, Memberships und digitale Angebote verkaufen oder Sessions, Workshops und Studiozeiten anbieten und buchen."],["Dein Bereich. Deine Grenzen.","Keine feste Rolle nötig: Nutze nur die Funktionen, die zu dir, deinen Interessen und deinen einvernehmlichen Dynamiken passen."]],
    creator:{kicker:"FÜR CREATOR & ANBIETER",title:"Deine Präsenz. Dein Content. Deine Sessions.",lead:"Egal ob Domina, Rigger, Shibari-Artist, Latex-Creator, Fetisch-Model oder anderer Kink-Creator: Du kannst deine eigene Präsenz aufbauen, Content verkaufen und Sessions oder Workshops zentral organisieren.",features:[["Eigene House-Präsenz","Profil, Bio, Kinks, Medien, Angebote und öffentliche Informationen an einem Ort."],["Content verkaufen","Fotos, Videos, digitale Inhalte und exklusive Angebote für deine Community bereitstellen."],["Sessions & Workshops","Studio-Sessions, Shibari, Bondage, Fetisch-Sessions, Workshops oder andere buchbare Erlebnisse anbieten."],["Discover & Reichweite","Über Interessen, Kinks, Standort und Angebote gefunden werden – nicht nur über eine D/s-Rolle."],["Kalender & Verfügbarkeit","Termine, Studiozeiten, Workshops und persönliche Sessions planen und in deinen Kalender übernehmen."],["Nachrichten & private Bereiche","Direkte Kommunikation und geschützte Bereiche für individuelle Kontakte oder Dynamiken."],["Memberships & Community","Abos, exklusive Inhalte, Vorteile und wiederkehrende Angebote für deine Community erstellen."],["Finanzen & Verwaltung","Umsätze, Buchungen und Plattformaktivitäten zentral nachvollziehen."]]},
    member:{kicker:"FÜR MEMBERS & ENTDECKER",title:"Entdecke, was zu deinem Kink passt.",lead:"Du musst weder Sub noch Sklave sein. Entdecke Creator, Kinks, Content, Sessions und Communities, speichere Favoriten, buche Angebote und entscheide selbst, welche Bereiche du nutzen möchtest.",features:[["Discover","Creator, Session-Anbieter und Members nach Kink, Ort, Angebot und Interessen entdecken."],["Content & Memberships","Content ansehen, Creator unterstützen und exklusive Memberships abonnieren."],["Sessions buchen","Shibari, Bondage, Fetisch-, Studio- oder andere Sessions und Workshops buchen."],["Favoriten & Interessen","Profile und Angebote speichern und schneller wiederfinden, was zu deinen Interessen passt."],["Nachrichten","Direkt und privat innerhalb des House kommunizieren."],["Kalender","Gebuchte Sessions, Termine, Workshops und House-Ereignisse übersichtlich verfolgen."],["Optionale Dynamiken","D/s, Aufgaben, Keuschhaltung, Regeln oder andere strukturierte Dynamiken nur dann nutzen, wenn du sie möchtest."],["Consent & Grenzen","Eigene Interessen und Grenzen sichtbar und jederzeit anpassbar halten."]]},
    how:{kicker:"SO FUNKTIONIERT'S",title:"Von deinem Kink zum passenden Angebot.",steps:[["Entdecken","Creator, Members, Kinks, Content und Sessions über Discover kennenlernen."],["Nutzung wählen","Registriere dich zum Anbieten, Entdecken oder für beides – ohne dich auf Domina oder Sub festlegen zu müssen."],["Verbinden & buchen","Content, Memberships, Nachrichten, Buchungen und Kalender zentral nutzen."],["Dein House gestalten","Aktiviere genau die Bereiche, die du brauchst – von Content und Sessions bis zu optionalen D/s-Tools."]]},
    pay:{kicker:"ZAHLUNGEN & ABGABEN",title:"Transparent, bevor Geld fließt.",lead:"House of Doms trennt Memberships, Content, digitale Angebote, Online-Sessions, Studio-Sessions, Workshops und optionale Homepage-Leistungen klar voneinander.",teaserTitle:"Das komplette Gebührenmodell",teaserText:"Alle Prozentsätze, Zahlungsanbieter-Kosten, Homepage-Leistungen und Umsatzstufen übersichtlich auf einer eigenen Seite ansehen.",button:"GEBÜHRENMODELL ANSEHEN"},
    trust:{kicker:"VERTRAUEN & VIELFALT",title:"Ein Raum für erwachsene, einvernehmliche Kink-Communitys.",items:[["Alle Kinks willkommen","Von Shibari, Latex, Leder und Fußfetisch bis D/s, Bondage und weiteren Interessen – ohne Pflicht zu einer festen Rolle."],["Consent & Grenzen","Klare Absprachen, freiwillige Teilnahme und persönliche Grenzen gehören sichtbar zum Ablauf."],["Privatsphäre","Öffentlich ist nur, was öffentlich sein soll. Private Inhalte und Kontakte bleiben in geschützten Bereichen."]]},
    cta:{kicker:"DEIN EINTRITT",title:"Entdecke dein Kink-House – oder baue deine eigene Präsenz auf.",lead:"Starte als Creator, entdecke als Member oder nutze einfach beides.",creator:"ALS CREATOR STARTEN",member:"ENTDECKEN & BUCHEN",discover:"KINKS & CREATOR ENTDECKEN"}
  },
  en: {
    nav:{discover:"DISCOVER",creator:"FOR CREATORS",member:"FOR MEMBERS",how:"HOW IT WORKS",pay:"PAYMENTS",login:"LOGIN"},
    enter:"Enter House",
    flyingWords:["KINK","FETISH","SHIBARI","ROPE","LATEX","LEATHER","BONDAGE","FEET","DOMINANCE","DEVOTION","SWITCH","WORSHIP","CHASTITY","ROLEPLAY","SENSORY","PETPLAY","TRUST","CONSENT"],
    intro:{kicker:"HOUSE OF DOMS",title:"A House for kink, fetish, content and sessions.",lead:"House of Doms is not only for Dommes and subs. Creators, session providers, riggers, fetish lovers, switches and curious members can discover, sell, book, communicate and organise in one place."},
    why:[["Discover kinks","Explore profiles, content and sessions by interests such as Shibari, latex, bondage, foot fetish, D/s and many more kinks."],["Content & sessions","Sell photos, videos, memberships and digital offers, or provide and book sessions, workshops and studio time."],["Your space. Your boundaries.","No fixed role required: use only the tools that fit you, your interests and your consensual dynamics."]],
    creator:{kicker:"FOR CREATORS & PROVIDERS",title:"Your presence. Your content. Your sessions.",lead:"Whether you are a Domme, rigger, Shibari artist, latex creator, fetish model or another kink creator, build your presence, sell content and organise sessions or workshops centrally.",features:[["Your House presence","Profile, bio, kinks, media, offers and public information in one place."],["Sell content","Offer photos, videos, digital content and exclusive releases to your community."],["Sessions & workshops","Offer Shibari, bondage, fetish, studio or other sessions and workshops."],["Discover & reach","Be found by interests, kinks, location and offers rather than only by a D/s role."],["Calendar & availability","Plan appointments, studio time, workshops and personal sessions and sync your calendar."],["Messages & private spaces","Direct communication and protected areas for individual connections or dynamics."],["Memberships & community","Create subscriptions, exclusive content, benefits and recurring offers."],["Finances & management","Track revenue, bookings and platform activity centrally."]]},
    member:{kicker:"FOR MEMBERS & EXPLORERS",title:"Discover what fits your kink.",lead:"You do not have to identify as a sub. Discover creators, kinks, content, sessions and communities, save favourites, book offers and choose which areas you want to use.",features:[["Discover","Find creators, session providers and members by kink, location, offer and interests."],["Content & memberships","View content, support creators and subscribe to exclusive memberships."],["Book sessions","Book Shibari, bondage, fetish, studio and other sessions or workshops."],["Favourites & interests","Save profiles and offers and quickly return to what fits your interests."],["Messages","Communicate directly and privately inside the House."],["Calendar","Keep booked sessions, appointments, workshops and House events organised."],["Optional dynamics","Use D/s, tasks, chastity, rules or other structured dynamics only when you want them."],["Consent & boundaries","Keep your interests and boundaries visible and adjustable at any time."]]},
    how:{kicker:"HOW IT WORKS",title:"From your kink to the right offer.",steps:[["Discover","Explore creators, members, kinks, content and sessions through Discover."],["Choose how you use it","Register to offer, explore or do both without having to identify as Domme or sub."],["Connect & book","Use content, memberships, messages, bookings and calendars centrally."],["Shape your House","Activate only the areas you need, from content and sessions to optional D/s tools."]]},
    pay:{kicker:"PAYMENTS & FEES",title:"Transparent before money moves.",lead:"House of Doms clearly separates memberships, content, digital offers, online sessions, studio sessions, workshops and optional homepage services.",teaserTitle:"The complete fee model",teaserText:"View all percentages, payment provider costs, homepage services and revenue tiers on a dedicated page.",button:"VIEW FEE MODEL"},
    trust:{kicker:"TRUST & DIVERSITY",title:"A space for adult, consensual kink communities.",items:[["All kinks welcome","From Shibari, latex, leather and foot fetish to D/s, bondage and more, without forcing a fixed role."],["Consent & boundaries","Clear agreements, voluntary participation and personal boundaries are visible parts of the experience."],["Privacy","Only intended public information is public. Private content and contacts stay protected."]]},
    cta:{kicker:"YOUR ENTRY",title:"Discover your kink House – or build your own presence.",lead:"Start as a creator, explore as a member, or simply do both.",creator:"START AS CREATOR",member:"DISCOVER & BOOK",discover:"DISCOVER KINKS & CREATORS"}
  }
} as const;

export default function Home(){
  const router=useRouter();
  const [entering,setEntering]=useState(false);
  const [lang,setLang]=useState<Lang>("de");
  const [audience,setAudience]=useState<Audience>(null);
  const t=copy[lang];
  useEffect(()=>{const stored=window.localStorage.getItem("house-language");const initial:Lang=stored==="en"||stored==="de"?stored:navigator.language.toLowerCase().startsWith("en")?"en":"de";setLang(initial);document.documentElement.lang=initial},[]);
  function changeLanguage(next:Lang){setLang(next);window.localStorage.setItem("house-language",next);document.documentElement.lang=next}
  function enterHouse(){if(entering)return;setEntering(true);window.setTimeout(()=>router.push("/anmelden"),4600)}
  function chooseAudience(next:Exclude<Audience,null>){setAudience(next);window.setTimeout(()=>document.getElementById("roles")?.scrollIntoView({behavior:"smooth",block:"start"}),20)}
  const selected=audience==="creator"?t.creator:audience==="member"?t.member:null;

  return <main className="publicLanding">
    <section className={`referenceEntrance${entering?" isEntering":""}`}>
      <header className="referenceNav"><Link href="/" className="referenceBrand"><img src="/door-emblem.svg" alt=""/><span>HOUSE OF DOMS</span></Link><nav><Link href="/discover">{t.nav.discover}</Link><a href="#roles" onClick={()=>setAudience("creator")}>{t.nav.creator}</a><a href="#roles" onClick={()=>setAudience("member")}>{t.nav.member}</a><a href="#how">{t.nav.how}</a><a href="#payments">{t.nav.pay}</a></nav><div className="referenceNavActions"><button type="button" onClick={()=>changeLanguage(lang==="de"?"en":"de")}>{lang.toUpperCase()}</button><Link href="/anmelden">{t.nav.login}</Link></div></header>
      <nav className="marketingMobileNav" aria-label="Öffentliche Bereiche"><Link href="/discover">{t.nav.discover}</Link><a href="#roles" onClick={()=>setAudience("creator")}>{t.nav.creator}</a><a href="#roles" onClick={()=>setAudience("member")}>{t.nav.member}</a><a href="#how">{t.nav.how}</a><a href="#payments">{t.nav.pay}</a></nav>
      <div className="referenceScene"><div className="referenceBackdrop" aria-hidden="true"/><div className="referenceVignette" aria-hidden="true"/><button className="referenceDoorHotspot" type="button" onClick={enterHouse} aria-label={t.enter}/><div className="referenceDoorGlow" aria-hidden="true"/><div className="referenceWords" aria-hidden="true">{t.flyingWords.map((word,index)=><span key={`${lang}-${word}-${index}`} style={{"--word-index":index} as CSSProperties}>{word}</span>)}</div></div>
    </section>
    <div className="marketingBody">
      <section className="marketingSection marketingIntro" id="discover-info"><div><span className="marketingKicker">{t.intro.kicker}</span><h2>{t.intro.title}</h2><p className="marketingLead">{t.intro.lead}</p></div><div className="marketingIntroActions"><Link className="marketingButton primary" href="/discover">{t.cta.discover}</Link><Link className="marketingButton" href="/anmelden">{t.nav.login}</Link></div></section>
      <section className="marketingSection"><span className="marketingKicker">KINK · CONTENT · SESSIONS · COMMUNITY</span><div className="marketingGrid">{t.why.map(([title,text])=><article className="marketingCard" key={title}><strong>{title}</strong><p>{text}</p></article>)}</div></section>

      <section className="marketingSection roleSelectorSection" id="roles">
        <div className="roleSelectorIntro"><span className="marketingKicker">{lang==="de"?"WIE MÖCHTEST DU DAS HOUSE NUTZEN?":"HOW DO YOU WANT TO USE THE HOUSE?"}</span><h2>{lang==="de"?"Keine feste Rolle nötig.":"No fixed role required."}</h2><p>{lang==="de"?"Wähle, was du tun möchtest. D/s-Rollen und spezielle Dynamiken bleiben möglich, sind aber keine Voraussetzung.":"Choose what you want to do. D/s roles and specialised dynamics remain available, but they are never required."}</p></div>
        <div className="roleSelectorGrid">
          <button type="button" className={`roleSelectorCard${audience==="creator"?" active":""}`} onClick={()=>chooseAudience("creator")}><span>{lang==="de"?"ICH MÖCHTE":"I WANT TO"}</span><strong>{lang==="de"?"Content & Sessions anbieten":"Offer content & sessions"}</strong><p>{lang==="de"?"Creator-Profil, Content, Sessions, Kalender, Memberships, Reichweite und Finanzen ansehen.":"See creator profiles, content, sessions, calendars, memberships, reach and finances."}</p><b>→</b></button>
          <button type="button" className={`roleSelectorCard${audience==="member"?" active":""}`} onClick={()=>chooseAudience("member")}><span>{lang==="de"?"ICH MÖCHTE":"I WANT TO"}</span><strong>{lang==="de"?"Entdecken, folgen & buchen":"Discover, follow & book"}</strong><p>{lang==="de"?"Kinks, Creator, Content, Sessions, Favoriten, Memberships und optionale Dynamiken ansehen.":"See kinks, creators, content, sessions, favourites, memberships and optional dynamics."}</p><b>→</b></button>
        </div>
        {selected&&<div className="roleReveal"><div className="roleHead"><div><span className="marketingKicker">{selected.kicker}</span><h2>{selected.title}</h2></div><p className="marketingLead">{selected.lead}</p></div><div className="roleFeatures">{selected.features.map(([title,text])=><article className="roleFeature" key={title}><b>{title}</b><span>{text}</span></article>)}</div></div>}
      </section>

      <section className="marketingSection roleSection" id="how"><span className="marketingKicker">{t.how.kicker}</span><h2>{t.how.title}</h2><div className="workflow">{t.how.steps.map(([title,text])=><article key={title}><b>{title}</b><p>{text}</p></article>)}</div></section>
      <section className="marketingSection roleSection" id="payments"><span className="marketingKicker">{t.pay.kicker}</span><h2>{t.pay.title}</h2><p className="marketingLead">{t.pay.lead}</p><div className="feeTeaser"><div><strong>{t.pay.teaserTitle}</strong><p>{t.pay.teaserText}</p></div><Link className="marketingButton primary feeModelLink" href="/gebuehrenmodell">{t.pay.button}</Link></div></section>
      <section className="marketingSection roleSection"><span className="marketingKicker">{t.trust.kicker}</span><h2>{t.trust.title}</h2><div className="trustStrip">{t.trust.items.map(([title,text])=><article key={title}><b>{title}</b><p>{text}</p></article>)}</div></section>
      <section className="marketingSection marketingCta"><span className="marketingKicker">{t.cta.kicker}</span><h2>{t.cta.title}</h2><p className="marketingLead">{t.cta.lead}</p><div className="marketingIntroActions"><Link className="marketingButton primary" href="/anmelden?tab=register&rolle=creator">{t.cta.creator}</Link><Link className="marketingButton" href="/anmelden?tab=register&rolle=member">{t.cta.member}</Link><Link className="marketingButton" href="/discover">{t.cta.discover}</Link></div></section>
      <footer className="marketingFooter">HOUSE OF DOMS · 18+ · KINK · CONSENT · PRIVACY · COMMUNITY</footer>
    </div>
  </main>
}
