"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "../../../lib/supabase/client";
import "./manage-studio.css";

type D={id:string;house_id:string;event_date:string;starts_at:string;ends_at:string;studio_name:string;room:string|null;is_duo:boolean;duo_partner:string|null;is_content_shoot:boolean;internal_note:string|null;buffer_minutes:number;is_hidden:boolean;price_cents:number|null};
const tm=(v:string)=>v?.slice(0,5)||"";
const addWeek=(date:string)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)};

export default function StudioManager(){
 const [rows,setRows]=useState<D[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 async function load(){const s=createClient();const {data:auth}=await s.auth.getUser();if(!auth.user){location.href="/anmelden";return}const {data:p}=await s.from("profiles").select("role").eq("id",auth.user.id).maybeSingle();if(!["dom","domina"].includes(String(p?.role||""))){setMsg("Nur Dom/Domina kann Studiozeiten verwalten.");setLoading(false);return}const {data,error}=await s.rpc("get_my_studio_windows_admin");if(error)setMsg(error.message);else setRows((data||[]) as D[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 return <main className="studioManagePage"><header><div><Link href="/kalender">← Kalender</Link><span>DOM / DOMINA · STUDIO CONTROL</span><h1>Studiozeiten verwalten</h1><p>Bestehende Zeitfenster bearbeiten, Konflikte vermeiden oder eine Woche weiter kopieren.</p></div><Link className="newWindow" href="/kalender">+ Neues Zeitfenster</Link></header>{msg&&<p className="manageMsg">{msg}</p>}{loading?<section className="manageEmpty">Studiozeiten werden geladen …</section>:rows.length===0?<section className="manageEmpty">Noch keine Studiozeiten vorhanden.</section>:<section className="manageGrid">{rows.map(row=><WindowEditor key={row.id} row={row} reload={load} setMsg={setMsg}/>)}</section>}</main>
}

function WindowEditor({row,reload,setMsg}:{row:D;reload:()=>Promise<void>;setMsg:(x:string)=>void}){
 const [edit,setEdit]=useState(false),[saving,setSaving]=useState(false),[date,setDate]=useState(row.event_date),[start,setStart]=useState(tm(row.starts_at)),[end,setEnd]=useState(tm(row.ends_at)),[studio,setStudio]=useState(row.studio_name),[room,setRoom]=useState(row.room||""),[duo,setDuo]=useState(Boolean(row.is_duo)),[partner,setPartner]=useState(row.duo_partner||""),[content,setContent]=useState(Boolean(row.is_content_shoot)),[note,setNote]=useState(row.internal_note||""),[buffer,setBuffer]=useState(row.buffer_minutes??45),[hidden,setHidden]=useState(Boolean(row.is_hidden)),[price,setPrice]=useState(row.price_cents==null?"":String(row.price_cents/100).replace(".",","));
 async function save(e:FormEvent){e.preventDefault();setSaving(true);const s=createClient();const {data:conflicts,error:conflictError}=await s.rpc("check_my_studio_window_conflicts",{p_event_date:date,p_starts_at:start,p_ends_at:end,p_exclude_id:row.id});if(conflictError){setSaving(false);setMsg(conflictError.message);return}if((conflicts||[]).length){setSaving(false);setMsg(`Konflikt mit ${(conflicts||[]).map((x:any)=>`${tm(x.starts_at)}–${tm(x.ends_at)} ${x.studio_name}`).join(", ")}`);return}const {error}=await s.rpc("update_my_studio_window_advanced",{p_id:row.id,p_event_date:date,p_starts_at:start,p_ends_at:end,p_studio_name:studio,p_room:room||null,p_is_duo:duo,p_duo_partner:duo?partner||null:null,p_is_content_shoot:content,p_internal_note:note||null,p_buffer_minutes:buffer,p_is_hidden:hidden,p_price_cents:price?Math.round(Number(price.replace(",","."))*100):null});setSaving(false);if(error){setMsg(error.message);return}setMsg("Studiozeit aktualisiert.");setEdit(false);await reload()}
 async function cloneWeek(){setSaving(true);const next=addWeek(row.event_date);const s=createClient();const {data:conflicts}=await s.rpc("check_my_studio_window_conflicts",{p_event_date:next,p_starts_at:tm(row.starts_at),p_ends_at:tm(row.ends_at),p_exclude_id:null});if((conflicts||[]).length){setSaving(false);setMsg(`Nächste Woche gibt es bereits einen Konflikt am ${next}.`);return}const {error}=await s.rpc("publish_advanced_studio_window",{p_event_date:next,p_starts_at:tm(row.starts_at),p_ends_at:tm(row.ends_at),p_studio_name:row.studio_name,p_room:row.room,p_is_duo:row.is_duo,p_duo_partner:row.duo_partner,p_is_content_shoot:row.is_content_shoot,p_internal_note:row.internal_note,p_buffer_minutes:row.buffer_minutes,p_is_hidden:row.is_hidden,p_price_cents:row.price_cents,p_second_starts_at:null,p_second_ends_at:null});setSaving(false);if(error){setMsg(error.message);return}setMsg(`Studiozeit auf ${next} dupliziert.`);await reload()}
 return <article className={`manageCard ${row.is_hidden?"hiddenWindow":""}`}><div className="manageCardHead"><div><span>{row.event_date} · {tm(row.starts_at)}–{tm(row.ends_at)}</span><h2>{row.studio_name}</h2><p>{row.room||"Kein Raum"} · Puffer {row.buffer_minutes??45} Min · {row.is_hidden?"intern":"für Subs sichtbar"}</p></div><b>{row.is_content_shoot?"CONTENT ":""}{row.is_duo?"DUO":""}</b></div>{edit?<form className="editWindow" onSubmit={save}><label>Datum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Von<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Bis<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="wide">Studio<input value={studio} onChange={e=>setStudio(e.target.value)}/></label><label>Raum<input value={room} onChange={e=>setRoom(e.target.value)}/></label><label>Preis €/h<input value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Puffer<input type="number" min={0} max={240} value={buffer} onChange={e=>setBuffer(Number(e.target.value)||0)}/></label><label className="check"><input type="checkbox" checked={duo} onChange={e=>setDuo(e.target.checked)}/> Duo</label>{duo&&<label>Duo-Partner<input value={partner} onChange={e=>setPartner(e.target.value)}/></label>}<label className="check"><input type="checkbox" checked={content} onChange={e=>setContent(e.target.checked)}/> Content</label><label className="check"><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/> Unsichtbar</label><label className="wide">Interne Notiz<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="editActions"><button disabled={saving}>{saving?"Speichert …":"Änderungen speichern"}</button><button type="button" onClick={()=>setEdit(false)}>Abbrechen</button></div></form>:<div className="manageActions"><button onClick={()=>setEdit(true)}>Bearbeiten</button><button onClick={()=>void cloneWeek()} disabled={saving}>↻ +1 Woche</button><Link href="/kalender">Im Kalender öffnen</Link></div>}</article>
}
