"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase/client";
import "../management.css";
type Kind="application"|"task"|"session"|"evidence"|"system";
type Item={id:string;kind:Kind;title:string;body:string;time:string;read:boolean;href:string};
const names:Record<Kind,string>={application:"Bewerbungen",task:"Aufgaben",session:"Sessions",evidence:"Nachweise",system:"System"};
export default function NotificationsPage(){
 const[items,setItems]=useState<Item[]>([]),[filter,setFilter]=useState<"all"|Kind|"unread">("all"),[loading,setLoading]=useState(true);
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();const{data:a}=await s.auth.getUser();if(!a.user){location.href="/anmelden?next=/benachrichtigungen";return}const rows:Item[]=[];const[{data:sessions},{data:tasks},{data:messages}]=await Promise.all([s.from("session_requests").select("id,creator_name,status,created_at").or(`requester_id.eq.${a.user.id},creator_id.eq.${a.user.id}`).order("created_at",{ascending:false}).limit(20),s.from("tasks").select("id,title,status,created_at").order("created_at",{ascending:false}).limit(20),s.from("messages").select("id,body,created_at").eq("recipient_id",a.user.id).order("created_at",{ascending:false}).limit(20)]);
 (sessions||[]).forEach((x:any)=>rows.push({id:"s"+x.id,kind:"session",title:x.status==="requested"?"Session-Anfrage":"Session aktualisiert",body:`${x.creator_name} · Status: ${x.status}`,time:new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.created_at)),read:false,href:"/sessions"}));
 (tasks||[]).forEach((x:any)=>rows.push({id:"t"+x.id,kind:"task",title:x.title||"Aufgabe",body:`Status: ${x.status||"offen"}`,time:new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.created_at)),read:true,href:"/aufgaben"}));
 (messages||[]).forEach((x:any)=>rows.push({id:"m"+x.id,kind:"system",title:"Neue Nachricht",body:String(x.body||"Private Nachricht").slice(0,120),time:new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.created_at)),read:false,href:"/kammer"}));
 setItems(rows);setLoading(false)}
 const visible=useMemo(()=>items.filter(i=>filter==="all"||filter==="unread"?!i.read:i.kind===filter),[items,filter]);const mark=(id:string)=>setItems(v=>v.map(i=>i.id===id?{...i,read:true}:i));const unread=items.filter(i=>!i.read).length;
 return <main className="managementPage"><header className="managementHero"><div><Link href="/hub" className="backLink">← Mein Bereich</Link><span className="eyebrow">HOUSE OF DOMS</span><h1>Benachrichtigungen</h1><p>Aktuelle Sessions, Aufgaben und Nachrichten aus deinem echten House-Konto.</p></div><button className="primaryAction" onClick={()=>setItems(v=>v.map(i=>({...i,read:true})))}>Alle als gelesen markieren</button></header><section className="statsRow"><article><span>Ungelesen</span><strong>{unread}</strong></article><article><span>Aktuell</span><strong>{items.length}</strong></article></section><section className="notificationLayout"><aside className="filterPanel"><h2>Filter</h2>{(["all","unread","task","session","system"] as const).map(v=><button key={v} className={filter===v?"selected":""} onClick={()=>setFilter(v)}>{v==="all"?"Alle":v==="unread"?"Ungelesen":names[v]}</button>)}</aside><div className="notificationFeed">{loading?<p className="emptyState">Wird geladen …</p>:visible.length===0?<p className="emptyState">Keine aktuellen Benachrichtigungen.</p>:visible.map(i=><article key={i.id} className={i.read?"read":"unread"}><button className="notificationMain" onClick={()=>mark(i.id)}><span className={`kindIcon ${i.kind}`}>{i.kind[0].toUpperCase()}</span><div><small>{names[i.kind]} · {i.time}</small><h2>{i.title}</h2><p>{i.body}</p></div>{!i.read&&<i/>}</button><Link href={i.href} onClick={()=>mark(i.id)}>Öffnen →</Link></article>)}</div></section></main>
}