"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import "./kammer.css";

type Contact={user_id:string;display_name:string;role:string;last_message:string;unread_count:number};
type Candidate={user_id:string;display_name:string;role:string};
type Msg={id:string;sender_id:string;recipient_id:string;body:string|null;attachment_type:"image"|"video"|"audio"|"file"|null;attachment_path:string|null;linked_task_id:string|null;linked_booking_id:string|null;reply_to_id:string|null;pinned_at:string|null;created_at:string};

export default function ChamberPage(){
 const params=useSearchParams();
 const [contacts,setContacts]=useState<Contact[]>([]); const [active,setActive]=useState(""); const [query,setQuery]=useState("");
 const [messages,setMessages]=useState<Msg[]>([]); const [draft,setDraft]=useState(""); const [me,setMe]=useState(""); const [replying,setReplying]=useState<Msg|null>(null);
 const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [notice,setNotice]=useState("");
 const [pendingFile,setPendingFile]=useState<File|null>(null); const imageRef=useRef<HTMLInputElement>(null); const videoRef=useRef<HTMLInputElement>(null); const audioRef=useRef<HTMLInputElement>(null); const fileRef=useRef<HTMLInputElement>(null);
 const [showNew,setShowNew]=useState(false); const [candidateQuery,setCandidateQuery]=useState(""); const [candidates,setCandidates]=useState<Candidate[]>([]); const [searching,setSearching]=useState(false);

 const loadContacts=useCallback(async()=>{const supabase=createClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user){location.href="/anmelden";return;}setMe(auth.user.id);const {data,error}=await supabase.rpc("get_chamber_contacts");if(error){setNotice(`Supabase: ${error.message}`);setLoading(false);return;}const list=(data||[]) as Contact[];setContacts(list);const fromUrl=params.get("contact")||"";setActive(v=>v||fromUrl||list[0]?.user_id||"");setLoading(false);},[params]);
 const loadMessages=useCallback(async(id:string)=>{if(!id)return;const supabase=createClient();const {data,error}=await supabase.rpc("get_chamber_messages_v2",{p_other_user:id});if(error){setNotice(`Supabase: ${error.message}`);return;}setMessages((data||[]) as Msg[]);},[]);
 const searchCandidates=useCallback(async(q:string)=>{setSearching(true);setNotice("");const supabase=createClient();const {data,error}=await supabase.rpc("search_chamber_contacts",{p_query:q});setSearching(false);if(error){setNotice(`Supabase: ${error.message}`);return;}setCandidates((data||[]) as Candidate[]);},[]);
 useEffect(()=>{void loadContacts();},[loadContacts]); useEffect(()=>{if(active)void loadMessages(active);else setMessages([]);setReplying(null);},[active,loadMessages]);
 useEffect(()=>{if(showNew)void searchCandidates(candidateQuery);},[showNew,candidateQuery,searchCandidates]);
 const filtered=useMemo(()=>contacts.filter(c=>c.display_name.toLowerCase().includes(query.toLowerCase())),[contacts,query]);
 const contact=contacts.find(c=>c.user_id===active) || candidates.find(c=>c.user_id===active);
 const pinned=messages.filter(m=>m.pinned_at).sort((a,b)=>new Date(b.pinned_at||0).getTime()-new Date(a.pinned_at||0).getTime());
 const byId=useMemo(()=>new Map(messages.map(m=>[m.id,m])),[messages]);

 function attachmentKind(file:File){if(file.type.startsWith("video/"))return "video";if(file.type.startsWith("image/"))return "image";if(file.type.startsWith("audio/"))return "audio";return "file";}
 async function send(e:FormEvent){e.preventDefault();if(!active||(!draft.trim()&&!pendingFile))return;setSending(true);setNotice("");const supabase=createClient();let path:string|null=null;let type:string|null=null;try{
   if(pendingFile){type=attachmentKind(pendingFile);const safe=pendingFile.name.replace(/[^a-zA-Z0-9._-]/g,"-");path=`${me}/${active}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from("chamber-media").upload(path,pendingFile,{contentType:pendingFile.type||"application/octet-stream",upsert:false});if(uploadError)throw uploadError;}
   const {error}=await supabase.rpc("send_chamber_message_v2",{p_recipient_id:active,p_body:draft.trim()||null,p_attachment_type:type,p_attachment_path:path,p_linked_task_id:null,p_linked_booking_id:null,p_reply_to_id:replying?.id||null});if(error)throw error;
   setDraft("");setPendingFile(null);setReplying(null);setShowNew(false);await loadMessages(active);await loadContacts();
 }catch(err:any){setNotice(`Supabase: ${err?.message||"Senden fehlgeschlagen"}`);}finally{setSending(false);}}
 async function openAttachment(msg:Msg){if(!msg.attachment_path)return;const supabase=createClient();const {data,error}=await supabase.storage.from("chamber-media").createSignedUrl(msg.attachment_path,300);if(error){setNotice(`Supabase: ${error.message}`);return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 async function togglePin(msg:Msg){const supabase=createClient();const {error}=await supabase.rpc("toggle_chamber_message_pin",{p_message_id:msg.id});if(error){setNotice(`Supabase: ${error.message}`);return;}await loadMessages(active)}
 function chooseFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0]||null;setPendingFile(file);e.target.value="";}
 function chooseCandidate(c:Candidate){setActive(c.user_id);setShowNew(false);setCandidateQuery("");setMessages([]);}
 function mediaLabel(m:Msg){return m.attachment_type==="video"?"🎥 Video öffnen":m.attachment_type==="audio"?"🎙 Sprachnachricht öffnen":m.attachment_type==="file"?"📎 Datei öffnen":"🖼 Bild öffnen"}

 return <main className="chamberPage"><section className="chamberShell">
  <aside className="threadRail"><div className="railHead"><span className="eyebrow">PRIVATE KAMMER</span><h1>Nachrichten</h1><button type="button" className="newConversationButton" onClick={()=>setShowNew(v=>!v)}>＋ Neue Nachricht</button><input placeholder="Chats durchsuchen …" value={query} onChange={e=>setQuery(e.target.value)}/></div>
   {showNew&&<div className="newConversationPanel"><input autoFocus placeholder="Nutzer suchen …" value={candidateQuery} onChange={e=>setCandidateQuery(e.target.value)}/>{searching?<p className="chamberEmpty">Suche …</p>:candidates.length===0?<p className="chamberEmpty">Keine weiteren Profile gefunden. Zum Testen brauchst du mindestens einen zweiten registrierten Nutzer.</p>:candidates.map(c=><button key={c.user_id} className="threadButton" onClick={()=>chooseCandidate(c)}><span className="threadAvatar">{c.display_name.slice(0,2).toUpperCase()}</span><span className="threadCopy"><strong>{c.display_name}</strong><small>{c.role}</small></span></button>)}</div>}
   <div className="threadList">{loading?<p className="chamberEmpty">Kontakte werden geladen …</p>:filtered.length===0?<p className="chamberEmpty">Noch keine Chats. Nutze „Neue Nachricht“, um einen Kontakt auszuwählen.</p>:filtered.map(c=><button key={c.user_id} className={active===c.user_id?"threadButton active":"threadButton"} onClick={()=>setActive(c.user_id)}><span className="threadAvatar">{c.display_name.slice(0,2).toUpperCase()}</span><span className="threadCopy"><strong>{c.display_name}</strong><small>{c.last_message}</small></span>{Number(c.unread_count)>0&&<em>{c.unread_count}</em>}</button>)}</div>
  </aside>
  <section className="conversationPane">{contact?<><header className="conversationHead"><div><strong>{contact.display_name}</strong><span>{contact.role} · Private Verbindung</span></div><div className="headActions"><Link className="headButton" href={`/profil?user=${contact.user_id}`}>Profil</Link><Link className="headButton" href={`/sub-akte/${contact.user_id}`}>Akte</Link></div></header>
   {notice&&<div className="chamberNotice">{notice}</div>}
   {pinned.length>0&&<div className="chamberNotice"><strong>◆ Angeheftet:</strong> {pinned.slice(0,2).map(m=>m.body||mediaLabel(m)).join(" · ")}</div>}
   <div className="messageStream">{messages.length===0&&<p className="chamberEmpty">Noch keine Nachrichten. Schreib die erste Nachricht.</p>}{messages.map(m=>{const parent=m.reply_to_id?byId.get(m.reply_to_id):null;return <div key={m.id} className={m.sender_id===me?"msgBubble mine":"msgBubble theirs"}>{parent&&<div style={{fontSize:11,opacity:.65,borderLeft:"2px solid currentColor",paddingLeft:8,marginBottom:7}}>↩ {parent.body||mediaLabel(parent)}</div>}{m.pinned_at&&<span style={{fontSize:10,opacity:.7}}>◆ ANGEHEFTET</span>}{m.body&&<p>{m.body}</p>}{m.attachment_path&&<button className="mediaMessage" onClick={()=>void openAttachment(m)}>{mediaLabel(m)}</button>}{m.linked_task_id&&<Link className="taskMessageLink" href="/aufgaben">📋 Aufgabe öffnen</Link>}{m.linked_booking_id&&<Link className="taskMessageLink" href="/kalender">◷ Session öffnen</Link>}<div style={{display:"flex",gap:8,alignItems:"center",justifyContent:"space-between"}}><small>{new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"}).format(new Date(m.created_at))}</small><span><button type="button" onClick={()=>setReplying(m)} style={{background:"transparent",border:0,color:"inherit",opacity:.7,cursor:"pointer"}}>Antworten</button><button type="button" onClick={()=>void togglePin(m)} style={{background:"transparent",border:0,color:"inherit",opacity:.7,cursor:"pointer"}}>{m.pinned_at?"Lösen":"Anheften"}</button></span></div></div>})}</div>
   {replying&&<div className="chamberNotice"><strong>Antwort auf:</strong> {replying.body||mediaLabel(replying)} <button type="button" onClick={()=>setReplying(null)}>×</button></div>}
   <div className="attachmentPrep"><button type="button" onClick={()=>imageRef.current?.click()}>＋ Bild</button><button type="button" onClick={()=>videoRef.current?.click()}>＋ Video</button><button type="button" onClick={()=>audioRef.current?.click()}>＋ Audio</button><button type="button" onClick={()=>fileRef.current?.click()}>＋ Datei</button><Link className="attachLink" href="/aufgaben">＋ Aufgabe</Link><Link className="attachLink" href="/kalender">＋ Session</Link><input ref={imageRef} hidden type="file" accept="image/*" onChange={chooseFile}/><input ref={videoRef} hidden type="file" accept="video/*" onChange={chooseFile}/><input ref={audioRef} hidden type="file" accept="audio/*" onChange={chooseFile}/><input ref={fileRef} hidden type="file" accept="application/pdf,text/plain,.zip" onChange={chooseFile}/>{pendingFile?<span className="pendingFile">Ausgewählt: {pendingFile.name}</span>:<span>Medien, Sprachnachricht oder Datei auswählen und mit der Nachricht senden.</span>}</div>
   <form className="composerBar" onSubmit={send}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={replying?"Antwort schreiben …":"Nachricht schreiben …"}/><button disabled={sending||(!draft.trim()&&!pendingFile)}>{sending?"Sendet …":"Senden"}</button></form></>:<div className="noConversation"><strong>Private Kammer</strong><p>Noch kein Chat ausgewählt. Klicke links auf „Neue Nachricht“.</p>{notice&&<div className="chamberNotice">{notice}</div>}</div>}</section>
 </section></main>;
}
