"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "../../lib/supabase/client";
import "./kassenbuch.css";

type Entry={id:string;owner_id:string;entry_type:"income"|"expense";source:string;booking_id:string|null;payment_date:string|null;appointment_date:string|null;starts_at:string|null;ends_at:string|null;customer:string;studio:string;category:string|null;payment_method:string|null;planned_amount_cents:number;amount_cents:number;status:string;note:string|null;vat_rate:number;tags:string[];receipt_path:string|null;created_at:string;updated_at:string};
const eur=(c:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format((c||0)/100);
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=(v?:string|null)=>v?new Intl.DateTimeFormat("de-DE").format(new Date(`${v}T12:00:00`)):"—";
const sourceLabel=(s:string)=>({booking:"Buchung",manual:"Manuell",money_slave:"Zahlsklave",studio_rent:"Studiomiete",tribute:"Tribute",store:"Store"}[s]||s);

export default function CashbookPage(){
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [allowed,setAllowed]=useState<boolean|null>(null),[entries,setEntries]=useState<Entry[]>([]),[editing,setEditing]=useState<Entry|null>(null);
 const now=new Date(); const [month,setMonth]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`);
 const [typeFilter,setTypeFilter]=useState(""),[methodFilter,setMethodFilter]=useState(""),[search,setSearch]=useState("");
 const [entryType,setEntryType]=useState<"income"|"expense">("income"),[source,setSource]=useState("manual"),[date,setDate]=useState(today()),[customer,setCustomer]=useState(""),[studio,setStudio]=useState(""),[method,setMethod]=useState(""),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[category,setCategory]=useState(""),[vatRate,setVatRate]=useState("19"),[tags,setTags]=useState("");

 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const supabase=createClient();const {data:auth}=await supabase.auth.getUser();if(!auth.user){window.location.href="/anmelden";return;}const {data:isDom,error:roleError}=await supabase.rpc("cashbook_is_dom");if(roleError) throw roleError;setAllowed(Boolean(isDom));if(!isDom){setEntries([]);return;}await supabase.rpc("sync_my_cashbook_bookings");const {data,error}=await supabase.from("dom_cashbook_entries").select("*").order("payment_date",{ascending:false,nullsFirst:false}).order("appointment_date",{ascending:false,nullsFirst:false});if(error) throw error;setEntries((data||[]) as Entry[]);}catch(e:any){setMessage(`Supabase: ${e?.message||"Unbekannter Fehler"}`);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);

 const filtered=useMemo(()=>entries.filter(e=>{const d=e.payment_date||e.appointment_date||e.created_at.slice(0,10);const hay=`${e.customer} ${e.studio} ${e.category||""} ${e.payment_method||""} ${sourceLabel(e.source)} ${(e.tags||[]).join(" ")}`.toLowerCase();return (!month||d.startsWith(month))&&(!typeFilter||e.entry_type===typeFilter)&&(!methodFilter||e.payment_method===methodFilter)&&(!search||hay.includes(search.toLowerCase()));}),[entries,month,typeFilter,methodFilter,search]);
 const methods=useMemo(()=>[...new Set(entries.map(e=>e.payment_method).filter(Boolean) as string[])].sort(),[entries]);
 const totals=useMemo(()=>filtered.reduce((a,e)=>{if(e.entry_type==="income")a.income+=e.amount_cents;else a.expense+=e.amount_cents;const rate=Number(e.vat_rate||0);if(e.entry_type==="income"&&rate>0){const net=Math.round(e.amount_cents/(1+rate/100));a.net+=net;a.vat+=e.amount_cents-net}else if(e.entry_type==="income")a.net+=e.amount_cents;return a;},{income:0,expense:0,net:0,vat:0}),[filtered]);

 function reset(){setEditing(null);setEntryType("income");setSource("manual");setDate(today());setCustomer("");setStudio("");setMethod("");setAmount("");setNote("");setCategory("");setVatRate("19");setTags("");}
 function edit(e:Entry){setEditing(e);setEntryType(e.entry_type);setSource(e.source);setDate(e.payment_date||e.appointment_date||today());setCustomer(e.customer);setStudio(e.studio);setMethod(e.payment_method||"");setAmount(String((e.amount_cents||e.planned_amount_cents||0)/100).replace(".",","));setNote(e.note||"");setCategory(e.category||"");setVatRate(String(e.vat_rate??0).replace(".",","));setTags((e.tags||[]).join(", "));window.scrollTo({top:0,behavior:"smooth"});}
 async function save(ev:FormEvent){ev.preventDefault();setSaving(true);setMessage("");try{const supabase=createClient();const cents=Math.round((Number(amount.replace(",","."))||0)*100);const vat=Number(vatRate.replace(",","."))||0;if(cents<0)throw new Error("Betrag ist ungültig.");if(vat<0||vat>100)throw new Error("MwSt.-Satz ist ungültig.");const payload={entry_type:entryType,source,payment_date:date||null,customer:customer.trim()||(entryType==="expense"?"Ausgabe":"Manueller Eintrag"),studio:studio.trim(),category:category.trim()||(entryType==="expense"?(source==="studio_rent"?"Studiomiete":"Ausgabe"):(source==="money_slave"?"Zahlsklave":"Einnahme")),payment_method:method.trim()||null,amount_cents:cents,planned_amount_cents:editing?.planned_amount_cents||cents,status:"completed",note:note.trim()||null,vat_rate:vat,tags:tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,20),updated_at:new Date().toISOString()};if(editing){const {error}=await supabase.from("dom_cashbook_entries").update(payload).eq("id",editing.id);if(error)throw error;}else{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Nicht angemeldet.");const {error}=await supabase.from("dom_cashbook_entries").insert({...payload,owner_id:auth.user.id});if(error)throw error;}reset();setMessage(editing?"Eintrag aktualisiert.":"Eintrag gespeichert.");await load();}catch(e:any){setMessage(`Supabase: ${e?.message||"Fehler beim Speichern"}`);}finally{setSaving(false);}}
 async function remove(id:string){if(!confirm("Diesen Kassenbuch-Eintrag wirklich löschen?"))return;const supabase=createClient();const {error}=await supabase.from("dom_cashbook_entries").delete().eq("id",id);if(error){setMessage(`Supabase: ${error.message}`);return;}await load();}
 function exportCsv(){const head=["Zahlungsdatum","Vorgang","Typ","Kategorie","Kunde","Studio","Zahlungsart","Brutto","MwSt.%","Tags","Termin","Status","Notiz"];const rows=filtered.map(e=>[e.payment_date||"",sourceLabel(e.source),e.entry_type==="income"?"Einnahme":"Ausgabe",e.category||"",e.customer,e.studio,e.payment_method||"",(e.amount_cents/100).toFixed(2).replace(".",","),String(e.vat_rate??0).replace(".",","),(e.tags||[]).join(", "),e.appointment_date||"",e.status,e.note||""]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`kassenbuch-${month||"export"}.csv`;a.click();URL.revokeObjectURL(url);}

 if(loading)return <main className="cashPage"><section className="cashGate">Kassenbuch wird geladen …</section></main>;
 if(allowed===false)return <main className="cashPage"><section className="cashGate"><span>DOM/Domina Bereich</span><h1>Kassenbuch</h1><p>Dieser Bereich ist ausschließlich für Dom/Domina-Konten freigeschaltet.</p><Link href="/dashboard">← Zurück zum Dashboard</Link></section></main>;

 return <main className="cashPage"><header className="cashHero"><div><span className="cashEyebrow">DOMINA · FINANZCOCKPIT</span><h1>Kassenbuch</h1><p>Sessions, Zahlsklaven, Tribute, Studiokosten, Kategorien und Steueranteile an einem Ort. Bestätigte House-Buchungen werden automatisch vorgemerkt.</p></div><div className="cashActions"><button onClick={()=>window.print()}>Drucken / PDF</button><button onClick={exportCsv}>CSV Export</button></div></header>
 {message&&<div className="cashMessage">{message}</div>}
 <section className="cashStats"><article><span>Einnahmen</span><strong>{eur(totals.income)}</strong></article><article><span>Ausgaben</span><strong>{eur(totals.expense)}</strong></article><article><span>Saldo</span><strong>{eur(totals.income-totals.expense)}</strong></article><article><span>Netto / MwSt.</span><strong className="mini">{eur(totals.net)} / {eur(totals.vat)}</strong></article></section>
 <section className="cashLayout"><form className="cashPanel cashForm" onSubmit={save}><div className="cashPanelHead"><div><span className="cashEyebrow">{editing?"BEARBEITEN":"NEUER EINTRAG"}</span><h2>{editing?sourceLabel(editing.source):"Zahlung erfassen"}</h2></div>{editing&&<button type="button" onClick={reset}>Abbrechen</button>}</div><div className="segmented"><button type="button" className={entryType==="income"?"active":""} onClick={()=>{setEntryType("income");if(source==="studio_rent")setSource("manual")}}>Einnahme</button><button type="button" className={entryType==="expense"?"active":""} onClick={()=>{setEntryType("expense");setSource("studio_rent")}}>Ausgabe</button></div><label>Vorgang<select value={source} onChange={e=>setSource(e.target.value)} disabled={Boolean(editing?.booking_id)}>{entryType==="income"?<><option value="manual">Manuell</option><option value="money_slave">Zahlsklave</option><option value="tribute">Tribute</option><option value="store">Store</option>{editing?.booking_id&&<option value="booking">Buchung</option>}</>:<><option value="studio_rent">Studiomiete</option><option value="manual">Sonstige Ausgabe</option></>}</select></label><label>Zahlungsdatum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{entryType==="income"?"Kunde / Referenz":"Ausgabe / Referenz"}<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder={source==="money_slave"?"Name / Alias des Zahlsklaven":"Name oder Beschreibung"}/></label><label>Kategorie<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="z. B. Session, Studio, Material"/></label><label>Studio / Ort<input value={studio} onChange={e=>setStudio(e.target.value)} placeholder="Optional"/></label><label>Zahlungsart<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">— wählen —</option><option>Bar</option><option>Überweisung</option><option>PayPal</option><option>Revolut</option><option>Karte</option><option>Sonstiges</option></select></label><label>Betrag (€)<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label>MwSt. %<input inputMode="decimal" value={vatRate} onChange={e=>setVatRate(e.target.value)} placeholder="0 / 7 / 19"/></label><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Studio, München, Stammkunde"/></label><label>Notiz<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Interne Notiz …"/></label><button className="cashPrimary" disabled={saving}>{saving?"Speichert …":editing?"Änderungen speichern":"Eintrag speichern"}</button></form>
 <section className="cashPanel cashBook"><div className="cashPanelHead"><div><span className="cashEyebrow">MONATSÜBERSICHT</span><h2>Bewegungen</h2></div><span>{filtered.length} Einträge</span></div><div className="cashFilters"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Alle Typen</option><option value="income">Einnahmen</option><option value="expense">Ausgaben</option></select><select value={methodFilter} onChange={e=>setMethodFilter(e.target.value)}><option value="">Alle Zahlungsarten</option>{methods.map(m=><option key={m}>{m}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kunde, Studio, Kategorie, Tag …"/></div>{filtered.length===0?<div className="cashEmpty">Keine Einträge im gewählten Zeitraum.</div>:<div className="cashRows">{filtered.map(e=><article className={`cashRow ${e.entry_type}`} key={e.id}><div className="cashDate"><strong>{fmtDate(e.payment_date||e.appointment_date)}</strong><span>{e.starts_at?`${String(e.starts_at).slice(0,5)} Uhr`:sourceLabel(e.source)}</span></div><div className="cashMain"><div><strong>{e.customer||sourceLabel(e.source)}</strong><span>{e.category||sourceLabel(e.source)}{e.studio?` · ${e.studio}`:""}{e.payment_method?` · ${e.payment_method}`:""}{Number(e.vat_rate)>0?` · ${e.vat_rate}% MwSt.`:""}</span></div>{e.booking_id&&e.amount_cents===0&&e.planned_amount_cents>0&&<em>{eur(e.planned_amount_cents)} vorgemerkt</em>}{(e.tags||[]).length>0&&<p>{e.tags.map(t=>`#${t}`).join(" ")}</p>}{e.note&&<p>{e.note}</p>}</div><div className="cashAmount"><strong>{e.entry_type==="expense"?"−":"+"}{eur(e.amount_cents)}</strong><span>{e.status}</span></div><div className="cashRowActions"><button onClick={()=>edit(e)}>Bearbeiten</button>{!e.booking_id&&<button onClick={()=>void remove(e.id)}>Löschen</button>}</div></article>)}</div>}</section></section>
 </main>;
}
