"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {createClient} from "../../lib/supabase/client";
import "./admin.css";
type M={users:number;houses:number;messages:number;tasks:number;bookings:number;storage_objects:number};
type R={id:string;reporter_name:string;target_type:string;target_id:string;reason:string;details:string;status:string;created_at:string;reviewed_at:string|null};
export default function PlatformAdmin(){
 const[m,setM]=useState<M|null>(null),[reports,setReports]=useState<R[]>([]),[msg,setMsg]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();const[{data:metrics,error},{data:rows,error:re}]=await Promise.all([s.rpc("get_platform_admin_metrics"),s.rpc("get_platform_reports")]);if(error||re){setMsg("Kein Plattform-Admin-Zugriff.");return}setM((metrics||[])[0]||null);setReports((rows||[]) as R[])}
 async function setStatus(id:string,status:string){const s=createClient();const{error}=await s.rpc("review_platform_report",{p_report_id:id,p_status:status});if(error){setMsg(error.message);return}await load()}
 return <main className="platformAdmin"><header><Link href="/dashboard">← Dashboard</Link><span>PLATTFORM ADMIN</span><h1>House of Doms · Moderation & Systemstatus</h1><p>Nur für explizit freigeschaltete Plattform-Admins.</p></header>{msg&&<section className="adminGate">{msg}</section>}{m&&<><section className="adminGrid"><article><span>Nutzer</span><strong>{m.users}</strong></article><article><span>Houses</span><strong>{m.houses}</strong></article><article><span>Nachrichten</span><strong>{m.messages}</strong></article><article><span>Aufgaben</span><strong>{m.tasks}</strong></article><article><span>Buchungen</span><strong>{m.bookings}</strong></article><article><span>Storage-Dateien</span><strong>{m.storage_objects}</strong></article></section><section style={{marginTop:32,display:"grid",gap:12}}><h2>Offene Meldungen</h2>{reports.length===0?<p>Keine Meldungen vorhanden.</p>:reports.map(r=><article key={r.id} style={{border:"1px solid #3b3022",padding:18,borderRadius:12,background:"#0f0d0a"}}><small>{r.target_type.toUpperCase()} · {new Date(r.created_at).toLocaleString("de-DE")} · von {r.reporter_name}</small><h3>{r.reason}</h3><p>{r.details||"Keine weiteren Details."}</p><code>{r.target_id}</code><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button disabled={r.status==="reviewing"} onClick={()=>setStatus(r.id,"reviewing")}>In Prüfung</button><button disabled={r.status==="resolved"} onClick={()=>setStatus(r.id,"resolved")}>Erledigt</button><button disabled={r.status==="dismissed"} onClick={()=>setStatus(r.id,"dismissed")}>Verwerfen</button><strong style={{marginLeft:"auto"}}>{r.status}</strong></div></article>)}</section></>}</main>
}
