"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";
import "./public-site.css";

type Site={id:string;slug:string;display_name:string;headline:string;about_text:string;services_text:string;rules_text:string;pricing_text:string;faq_text:string;location_text:string;contact_note:string;theme:string;email_alias:string|null;instagram_url:string|null;website_url:string|null;seo_title:string|null;seo_description:string|null;accent_style:string|null;gallery_urls:string[]|null;hero_image_url:string|null;booking_cta_label:string|null;booking_url:string|null;testimonials:any[]|null;custom_domain:string|null;show_memberships:boolean;show_booking_cta:boolean};
type Plan={name:string;tagline:string;description:string;billing_interval:string;price_cents:number;trial_days:number;max_members:number|null;benefits:any;active_members:number};
const eur=(c:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format((c||0)/100);
const cycle=(x:string)=>x==="month"?"Monat":x==="quarter"?"Quartal":x==="year"?"Jahr":"einmalig";

export default function PublicDominaSite(){
 const params=useParams<{slug:string}>();const slug=String(params?.slug||"");const[site,setSite]=useState<Site|null>(null),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[text,setText]=useState("");
 useEffect(()=>{void load()},[slug]);
 useEffect(()=>{if(!site)return;document.title=site.seo_title||`${site.display_name} | House of Doms`;let meta=document.querySelector('meta[name="description"]') as HTMLMetaElement|null;if(!meta){meta=document.createElement("meta");meta.name="description";document.head.appendChild(meta)}meta.content=site.seo_description||site.headline||site.about_text.slice(0,155)},[site]);
 async function load(){if(!slug)return;const s=createClient();const{data,error}=await s.from("domina_sites").select("*").eq("slug",slug.toLowerCase()).eq("is_published",true).maybeSingle();if(error){setMessage(error.message);setLoading(false);return}const next=(data||null) as Site|null;setSite(next);if(next?.show_memberships){const{data:p}=await s.rpc("get_public_subscription_plans_for_site",{p_slug:slug});setPlans((p||[]) as Plan[])}setLoading(false)}
 async function contact(e:FormEvent){e.preventDefault();setMessage("");const s=createClient();const{error}=await s.rpc("submit_domina_site_inquiry",{p_slug:slug,p_sender_name:name,p_sender_email:email,p_message:text});if(error){setMessage(error.message);return}setName("");setEmail("");setText("");setMessage("Deine Anfrage wurde über House of Doms übermittelt.")}
 const faq=useMemo(()=>String(site?.faq_text||"").split("\n").map(x=>x.trim()).filter(Boolean).map(x=>{const[q,...r]=x.split("::");return{q:q.trim(),a:r.join("::").trim()}}).filter(x=>x.q),[site]);
 if(loading)return <main className="publicDomina loading">Homepage wird geladen …</main>;
 if(!site)return <main className="publicDomina missing"><h1>Seite nicht gefunden</h1><p>Diese Domina-Homepage ist nicht veröffentlicht.</p><a href="/discover">Zurück zu Discover</a></main>;
 const gallery=(site.gallery_urls||[]).filter(Boolean),testimonials=(site.testimonials||[]).filter((x:any)=>x?.text);const bookingHref=site.booking_url||"#kontakt";
 return <main className={`publicDomina ${site.theme} accent-${site.accent_style||"classic"}`}><nav><a href="/">HOUSE OF DOMS</a><div><a href="#about">Über mich</a>{gallery.length>0&&<a href="#galerie">Galerie</a>}{plans.length>0&&<a href="#membership">Membership</a>}<a href="#sessions">Sessions</a><a href="#kontakt">Kontakt</a></div></nav>
 <header style={site.hero_image_url?{backgroundImage:`linear-gradient(rgba(5,4,8,.35),rgba(5,4,8,.88)),url(${site.hero_image_url})`,backgroundSize:"cover",backgroundPosition:"center"}:{}}><span>PRIVATE PUBLIC PAGE · HOUSE OF DOMS</span><h1>{site.display_name}</h1><h2>{site.headline}</h2>{site.location_text&&<p>{site.location_text}</p>}<div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{site.show_booking_cta&&<a className="cta" href={bookingHref} target={site.booking_url?"_blank":undefined}>{site.booking_cta_label||"Session anfragen"}</a>}<a className="cta" href="#kontakt">Kontakt</a></div></header>
 <section id="about" className="publicSection"><span>ÜBER MICH</span><h3>Persönlich. Klar. Eigenständig.</h3><p>{site.about_text}</p></section>
 {gallery.length>0&&<section id="galerie" className="publicSection"><span>GALERIE</span><h3>Einblicke</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,marginTop:18}}>{gallery.map((url,i)=><img key={`${url}-${i}`} src={url} alt={`${site.display_name} Galerie ${i+1}`} loading="lazy" style={{width:"100%",aspectRatio:"4/3",objectFit:"cover",borderRadius:12,border:"1px solid rgba(255,255,255,.12)"}}/>)}</div></section>}
 <section id="sessions" className="split"><article><span>SESSIONS & ANGEBOT</span><h3>Was ich anbiete</h3><p>{site.services_text}</p>{site.show_booking_cta&&<a className="cta" href={bookingHref} target={site.booking_url?"_blank":undefined}>{site.booking_cta_label||"Session anfragen"}</a>}</article><article><span>REGELN & RAHMEN</span><h3>Was wichtig ist</h3><p>{site.rules_text}</p></article></section>
 {plans.length>0&&<section id="membership" className="publicSection"><span>MEMBERSHIPS</span><h3>Teil meines Houses werden</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginTop:20}}>{plans.map(p=><article key={p.name} style={{border:"1px solid rgba(255,255,255,.14)",borderRadius:16,padding:20,background:"rgba(0,0,0,.2)"}}><span>{p.tagline}</span><h3>{p.name}</h3><strong style={{fontSize:"1.7rem"}}>{eur(p.price_cents)} <small>/ {cycle(p.billing_interval)}</small></strong>{p.trial_days>0&&<p>{p.trial_days} Tage Testphase</p>}<p>{p.description}</p><ul>{(Array.isArray(p.benefits)?p.benefits:[]).map((b:any)=><li key={String(b)}>✓ {String(b)}</li>)}</ul><a className="cta" href="/anmelden">Membership ansehen</a></article>)}</div></section>}
 {testimonials.length>0&&<section className="publicSection"><span>STIMMEN</span><h3>Erfahrungen</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:14,marginTop:18}}>{testimonials.map((t:any,i)=><blockquote key={i} style={{margin:0,padding:20,border:"1px solid rgba(255,255,255,.12)",borderRadius:14}}><p>“{t.text}”</p><footer style={{textAlign:"left"}}>— {t.name||"Anonym"}</footer></blockquote>)}</div></section>}
 {(site.pricing_text||faq.length>0)&&<section className="split"><article><span>PREISE / TRIBUTE</span><h3>Rahmen</h3><p>{site.pricing_text}</p></article><article><span>FAQ</span><h3>Vorab wissen</h3>{faq.map((x,i)=><details key={i} style={{borderBottom:"1px solid rgba(255,255,255,.12)",padding:"10px 0"}}><summary style={{cursor:"pointer",fontWeight:700}}>{x.q}</summary>{x.a&&<p>{x.a}</p>}</details>)}</article></section>}
 <section id="kontakt" className="contactSection"><div><span>KONTAKT</span><h3>Kontakt über House of Doms</h3><p>{site.contact_note||"Sende eine diskrete Anfrage über das Kontaktformular."}</p>{site.email_alias&&<div className="mailAlias"><strong>{site.email_alias}</strong><small>House-of-Doms-Adresse</small></div>}{site.instagram_url&&<a href={site.instagram_url} target="_blank">Instagram ↗</a>}{site.website_url&&<a href={site.website_url} target="_blank">Weitere Website ↗</a>}</div><form onSubmit={contact}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>E-Mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Nachricht<textarea rows={6} value={text} onChange={e=>setText(e.target.value)} required/></label><button>Diskret anfragen</button>{message&&<p className="formMessage">{message}</p>}</form></section><footer>Powered by House of Doms · Nur für Erwachsene · Einvernehmlichkeit und klare Grenzen</footer></main>;
}
