"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import "./site-builder.css";

type Site = {slug:string;display_name:string;headline:string;about_text:string;services_text:string;rules_text:string;pricing_text:string;faq_text:string;location_text:string;contact_note:string;theme:string;email_alias:string|null;email_status?:string;instagram_url:string|null;website_url:string|null;is_published:boolean};
const empty:Site={slug:"",display_name:"",headline:"",about_text:"",services_text:"",rules_text:"",pricing_text:"",faq_text:"",location_text:"",contact_note:"",theme:"crimson",email_alias:null,instagram_url:null,website_url:null,is_published:false};

export default function HomepageBuilder(){
 const [site,setSite]=useState<Site>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [inquiries,setInquiries]=useState<any[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){
  const supabase=createClient(); const {data:auth}=await supabase.auth.getUser(); if(!auth.user){location.href="/anmelden";return;}
  const {data:profile}=await supabase.from("profiles").select("display_name,role").eq("id",auth.user.id).maybeSingle();
  if(!["dom","domina"].includes(String(profile?.role||""))){setMessage("Nur Dom/Domina kann den Homepage-Builder verwenden.");setLoading(false);return;}
  const {data}=await supabase.from("domina_sites").select("*").eq("owner_id",auth.user.id).maybeSingle();
  if(data) setSite(data as Site); else {const base=String(profile?.display_name||"domina").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");setSite({...empty,display_name:profile?.display_name||"",slug:base});}
  if(data?.id){const {data:inq}=await supabase.from("domina_site_inquiries").select("id,sender_name,sender_email,message,created_at,read_at").eq("site_id",data.id).order("created_at",{ascending:false});setInquiries(inq||[])}
  setLoading(false);
 }
 function field<K extends keyof Site>(key:K,value:Site[K]){setSite(v=>({...v,[key]:value}))}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const supabase=createClient();const {data,error}=await supabase.rpc("save_my_domina_site",{p_slug:site.slug,p_display_name:site.display_name,p_headline:site.headline,p_about_text:site.about_text,p_services_text:site.services_text,p_rules_text:site.rules_text,p_pricing_text:site.pricing_text,p_faq_text:site.faq_text,p_location_text:site.location_text,p_contact_note:site.contact_note,p_theme:site.theme,p_instagram_url:site.instagram_url||null,p_website_url:site.website_url||null,p_is_published:site.is_published});setSaving(false);if(error){setMessage(`Supabase: ${error.message}`);return;}const next=Array.isArray(data)?data[0]:data;if(next)setSite(next);setMessage("Homepage gespeichert.");}
 if(loading)return <main className="builderPage"><section className="builderCard">Homepage-Builder wird geladen …</section></main>;
 return <main className="builderPage"><header><div><Link href="/house-einstellungen">← House-Einstellungen</Link><span>DOMINA SITE BUILDER</span><h1>Deine eigene Homepage.</h1><p>Inhalte einmal pflegen und als eigenständige House-of-Doms-Seite veröffentlichen.</p></div>{site.slug&&<a className="previewLink" href={`/d/${site.slug}`} target="_blank">Öffentliche Seite öffnen ↗</a>}</header>{message&&<div className="builderMessage">{message}</div>}
 <section className="builderGrid"><form className="builderCard" onSubmit={save}><h2>Seite gestalten</h2><label>Öffentliche URL<div className="slugRow"><span>houseofdoms.de/</span><input value={site.slug} onChange={e=>field("slug",e.target.value)}/></div></label><label>Name<input value={site.display_name} onChange={e=>field("display_name",e.target.value)}/></label><label>Headline<input value={site.headline} onChange={e=>field("headline",e.target.value)}/></label><label>Über mich<textarea rows={5} value={site.about_text} onChange={e=>field("about_text",e.target.value)}/></label><label>Angebot / Sessions<textarea rows={5} value={site.services_text} onChange={e=>field("services_text",e.target.value)}/></label><label>Regeln & Rahmen<textarea rows={5} value={site.rules_text} onChange={e=>field("rules_text",e.target.value)}/></label><label>Preise / Tribute<textarea rows={4} value={site.pricing_text} onChange={e=>field("pricing_text",e.target.value)}/></label><label>FAQ<textarea rows={4} value={site.faq_text} onChange={e=>field("faq_text",e.target.value)}/></label><label>Ort / Region<input value={site.location_text} onChange={e=>field("location_text",e.target.value)}/></label><label>Kontakt-Hinweis<textarea rows={3} value={site.contact_note} onChange={e=>field("contact_note",e.target.value)}/></label><label>Instagram<input value={site.instagram_url||""} onChange={e=>field("instagram_url",e.target.value)}/></label><label>Weitere Website<input value={site.website_url||""} onChange={e=>field("website_url",e.target.value)}/></label><div className="themePicker"><strong>Design</strong>{["crimson","obsidian","gold"].map(t=><button type="button" className={site.theme===t?"active":""} onClick={()=>field("theme",t)} key={t}>{t}</button>)}</div><label className="publishToggle"><input type="checkbox" checked={site.is_published} onChange={e=>field("is_published",e.target.checked)}/>Homepage öffentlich veröffentlichen</label><button className="saveButton" disabled={saving}>{saving?"Speichert …":"Homepage speichern"}</button></form>
 <aside className={`builderCard sitePreview ${site.theme}`}><span className="eyebrow">LIVE-VORSCHAU</span><h2>{site.display_name||"Dein Name"}</h2><h3>{site.headline||"Deine Headline"}</h3><p>{site.about_text||"Hier erscheint dein Über-mich-Text."}</p><div className="previewSection"><strong>Sessions & Angebot</strong><p>{site.services_text||"Noch keine Angaben"}</p></div><div className="previewSection"><strong>Kontakt</strong><p>{site.email_alias||`${site.slug||"dein-name"}@houseofdoms.de`}</p><small>E-Mail-Adresse ist zunächst reserviert. Ein echtes Postfach/Weiterleitung wird separat aktiviert.</small></div><div className="previewSection"><strong>Status</strong><p>{site.is_published?"Öffentlich":"Noch nicht veröffentlicht"}</p></div></aside></section>
 <section className="builderCard inbox"><span className="eyebrow">KONTAKTANFRAGEN</span><h2>Posteingang der Homepage</h2>{inquiries.length===0?<p>Noch keine Kontaktanfragen.</p>:inquiries.map(i=><article key={i.id}><strong>{i.sender_name}</strong><a href={`mailto:${i.sender_email}`}>{i.sender_email}</a><p>{i.message}</p><small>{new Date(i.created_at).toLocaleString("de-DE")}</small></article>)}</section>
 </main>;
}