"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import "./growth.css";

type GrowthState={
  completed:string[]; verification:"not_started"|"pending"|"verified"; premium:boolean;
  notifications:Record<string,boolean>; referralCode:string; credits:number;
  homepage:{headline:string;subline:string;city:string;accent:string;domain:string};
  seo:{title:string;description:string;city:string;keywords:string};
  waitlist:string[]; reviews:{name:string;rating:number;text:string}[];
};

const initial:GrowthState={completed:[],verification:"not_started",premium:false,notifications:{messages:true,tasks:true,sessions:true,media:true,subscriptions:true},referralCode:"HOUSE-7F3K",credits:0,homepage:{headline:"Willkommen in meinem House",subline:"Führung. Struktur. Präsenz.",city:"Berlin",accent:"Gold",domain:""},seo:{title:"Domina bei House of Doms",description:"Profil, Sessions und Angebote bei House of Doms.",city:"Berlin",keywords:"Domina, BDSM, Sessions"},waitlist:[],reviews:[{name:"Verifizierter Gast",rating:5,text:"Klare Kommunikation und professioneller Ablauf."}]};

const dominaSteps=["Profil vervollständigen","Profilbild & Medien hinzufügen","Preise & Angebote festlegen","Studiozeiten eintragen","Abos konfigurieren","Zahlungsdaten prüfen","Homepage veröffentlichen","Verifizierung beantragen"];
const subSteps=["Profil vervollständigen","Interessen & Grenzen eintragen","Domina über Discover finden","Bewerbung senden","Benachrichtigungen aktivieren","Zahlungsart hinterlegen"];
const tabs=["Onboarding","Verifizierung","Statistik","Premium","Homepage","SEO","Referral","Credits","Abrechnung","Warteliste","Benachrichtigungen"] as const;
type Tab=typeof tabs[number];

export default function GrowthPage(){
  const [role,setRole]=useState("domina"); const [tab,setTab]=useState<Tab>("Onboarding"); const [state,setState]=useState<GrowthState>(initial); const [loaded,setLoaded]=useState(false);
  useEffect(()=>{const raw=localStorage.getItem("hod-growth-state"); if(raw){try{setState({...initial,...JSON.parse(raw)})}catch{}} setLoaded(true); (async()=>{try{const supabase=createClient();const {data}=await supabase.auth.getUser();const r=String(data.user?.user_metadata?.role||"domina").toLowerCase();setRole(r)}catch{}})()},[]);
  function save(next:GrowthState){setState(next);localStorage.setItem("hod-growth-state",JSON.stringify(next))}
  function toggleStep(x:string){save({...state,completed:state.completed.includes(x)?state.completed.filter(y=>y!==x):[...state.completed,x]})}
  const isSub=role==="sub"||role==="sklave"; const steps=isSub?subSteps:dominaSteps; const progress=Math.round((steps.filter(x=>state.completed.includes(x)).length/steps.length)*100);
  const metrics=useMemo(()=>({views:842+state.completed.length*31,clicks:214+state.reviews.length*9,bookings:37+state.waitlist.length,conversion:((37+state.waitlist.length)/(842+state.completed.length*31)*100).toFixed(1),subs:58,revenue:4210}),[state]);
  if(!loaded)return <main className="growthPage"><p>Lädt…</p></main>;
  return <main className="growthPage">
    <header className="growthHero"><Link href="/dashboard">← Dashboard</Link><span>HOUSE OF DOMS · GROWTH & BUSINESS</span><h1>Wachstum, Vertrauen<br/><em>und Umsatz.</em></h1><p>Onboarding, Verifizierung, Sichtbarkeit, Homepage, SEO, Empfehlungen, Credits, Abrechnung und Wartelisten an einem Ort.</p></header>
    <nav className="growthTabs">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>

    {tab==="Onboarding"&&<section className="growthPanel"><div className="panelHead"><div><span>START</span><h2>{isSub?"Dein Sub-Onboarding":"Dein Domina-Onboarding"}</h2></div><strong>{progress}%</strong></div><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="checkGrid">{steps.map(x=><button key={x} onClick={()=>toggleStep(x)} className={state.completed.includes(x)?"done":""}><b>{state.completed.includes(x)?"✓":"○"}</b><span>{x}</span></button>)}</div></section>}

    {tab==="Verifizierung"&&<section className="growthPanel"><div className="panelHead"><div><span>TRUST</span><h2>Verifizierung & Bewertungen</h2></div><strong className="status">{state.verification==="verified"?"VERIFIZIERT":state.verification==="pending"?"IN PRÜFUNG":"OFFEN"}</strong></div><p className="lead">Verifizierte Profile erhalten ein sichtbares Badge in Discover. Die Prüfung kann Identität, Volljährigkeit, Profilvollständigkeit und – falls angegeben – Studioinformationen umfassen.</p><div className="actionRow"><button className="gold" onClick={()=>save({...state,verification:"pending"})}>Verifizierung beantragen</button><button onClick={()=>save({...state,verification:"verified"})}>Demo: Prüfung bestätigen</button></div><h3>Bewertungen nach Sessions</h3><div className="reviewList">{state.reviews.map((r,i)=><article key={i}><b>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</b><strong>{r.name}</strong><p>{r.text}</p></article>)}</div></section>}

    {tab==="Statistik"&&<section className="growthPanel"><div className="panelHead"><div><span>ANALYTICS</span><h2>Deine Performance</h2></div><strong>30 TAGE</strong></div><div className="metricGrid"><article><span>Profilaufrufe</span><b>{metrics.views}</b></article><article><span>Klicks</span><b>{metrics.clicks}</b></article><article><span>Buchungen</span><b>{metrics.bookings}</b></article><article><span>Conversion</span><b>{metrics.conversion}%</b></article><article><span>Aktive Abos</span><b>{metrics.subs}</b></article><article><span>Umsatz</span><b>{metrics.revenue.toLocaleString("de-DE")} €</b></article></div><p className="hint">Die Oberfläche ist bereits vorbereitet; Live-Zahlen können später direkt aus Supabase/Payments gespeist werden.</p></section>}

    {tab==="Premium"&&<section className="growthPanel"><div className="panelHead"><div><span>DISCOVER</span><h2>Premium-Platzierung</h2></div><strong>{state.premium?"AKTIV":"INAKTIV"}</strong></div><div className="premiumBox"><div><h3>Featured Domina</h3><p>Hervorgehobene Platzierung in Discover, Premium-Badge, priorisierte Sichtbarkeit und mögliche Startseiten-Fläche.</p></div><button className="gold" onClick={()=>save({...state,premium:!state.premium})}>{state.premium?"Deaktivieren":"Premium vormerken"}</button></div><p className="hint">Die kostenpflichtige Aktivierung wird erst nach Zahlungsfreigabe verbindlich; die Sichtbarkeitslogik ist vorbereitet.</p></section>}

    {tab==="Homepage"&&<section className="growthPanel"><div className="panelHead"><div><span>HOMEPAGE</span><h2>Deine eigene House-Seite</h2></div><strong>PRO</strong></div><div className="formGrid"><label>Headline<input value={state.homepage.headline} onChange={e=>save({...state,homepage:{...state.homepage,headline:e.target.value}})}/></label><label>Unterzeile<input value={state.homepage.subline} onChange={e=>save({...state,homepage:{...state.homepage,subline:e.target.value}})}/></label><label>Stadt<input value={state.homepage.city} onChange={e=>save({...state,homepage:{...state.homepage,city:e.target.value}})}/></label><label>Akzent<select value={state.homepage.accent} onChange={e=>save({...state,homepage:{...state.homepage,accent:e.target.value}})}><option>Gold</option><option>Rot</option><option>Silber</option><option>Violett</option></select></label><label className="wide">Eigene Domain (optional)<input placeholder="lady-example.de" value={state.homepage.domain} onChange={e=>save({...state,homepage:{...state.homepage,domain:e.target.value}})}/></label></div><div className="homepagePreview"><span>{state.homepage.city}</span><h3>{state.homepage.headline}</h3><p>{state.homepage.subline}</p><button>SESSION ANFRAGEN</button></div></section>}

    {tab==="SEO"&&<section className="growthPanel"><div className="panelHead"><div><span>GOOGLE</span><h2>SEO für dein Profil</h2></div><strong>INDEX</strong></div><div className="formGrid"><label>Seitentitel<input value={state.seo.title} onChange={e=>save({...state,seo:{...state.seo,title:e.target.value}})}/></label><label>Stadt<input value={state.seo.city} onChange={e=>save({...state,seo:{...state.seo,city:e.target.value}})}/></label><label className="wide">Beschreibung<textarea value={state.seo.description} onChange={e=>save({...state,seo:{...state.seo,description:e.target.value}})}/></label><label className="wide">Keywords<input value={state.seo.keywords} onChange={e=>save({...state,seo:{...state.seo,keywords:e.target.value}})}/></label></div><div className="searchPreview"><small>house-of-doms.com › discover › dein-profil</small><h3>{state.seo.title} · {state.seo.city}</h3><p>{state.seo.description}</p></div></section>}

    {tab==="Referral"&&<section className="growthPanel"><div className="panelHead"><div><span>EMPFEHLEN</span><h2>Referral-Programm</h2></div><strong>+ REICHWEITE</strong></div><p className="lead">Dominas können andere Dominas werben. Als Belohnung eignen sich z. B. ein kostenloser Pro-Monat oder Plattform-Credits. Subs können Credits für erfolgreiche Empfehlungen erhalten.</p><div className="codeBox"><span>DEIN CODE</span><b>{state.referralCode}</b><button onClick={()=>navigator.clipboard?.writeText(state.referralCode)}>Code kopieren</button></div></section>}

    {tab==="Credits"&&<section className="growthPanel"><div className="panelHead"><div><span>HOUSE BALANCE</span><h2>Credits & Guthaben</h2></div><strong>{state.credits.toFixed(2)} €</strong></div><p className="lead">House Credits können später für Medien, Tribute, Abos, Sessions oder Empfehlungsprämien verwendet werden. Die UI ist getrennt von echtem Bankguthaben.</p><div className="actionRow"><button onClick={()=>save({...state,credits:state.credits+10})}>Demo +10 Credits</button><button onClick={()=>save({...state,credits:Math.max(0,state.credits-5)})}>Demo −5 Credits</button></div><div className="ledger"><div><span>Referral-Bonus</span><b>+10,00 €</b></div><div><span>Premium-Vormerkung</span><b>−5,00 €</b></div></div></section>}

    {tab==="Abrechnung"&&<section className="growthPanel"><div className="panelHead"><div><span>FINANZEN</span><h2>Abrechnung & Rechnungen</h2></div><strong>TRANSPARENT</strong></div><div className="invoice"><div><span>Bruttoumsatz</span><b>4.210,00 €</b></div><div><span>Plattformgebühren</span><b>−621,50 €</b></div><div><span>Zahlungsanbieter (Domina)</span><b>−118,40 €</b></div><div className="total"><span>Voraussichtliche Auszahlung</span><b>3.470,10 €</b></div></div><div className="actionRow"><button onClick={()=>window.print()}>Abrechnung drucken / als PDF</button><Link className="buttonLink" href="/gebuehren">Gebührenmodell öffnen</Link></div></section>}

    {tab==="Warteliste"&&<section className="growthPanel"><div className="panelHead"><div><span>AUSGEBUCHT?</span><h2>Warteliste</h2></div><strong>{state.waitlist.length}</strong></div><div className="actionRow"><button className="gold" onClick={()=>save({...state,waitlist:[...state.waitlist,`Interessent ${state.waitlist.length+1}`]})}>Demo-Eintrag hinzufügen</button><Link className="buttonLink" href="/events">Events öffnen</Link></div><div className="waitList">{state.waitlist.length===0?<p>Noch niemand auf der Warteliste.</p>:state.waitlist.map((x,i)=><div key={i}><span>{i+1}</span><b>{x}</b><button onClick={()=>save({...state,waitlist:state.waitlist.filter((_,n)=>n!==i)})}>Entfernen</button></div>)}</div></section>}

    {tab==="Benachrichtigungen"&&<section className="growthPanel"><div className="panelHead"><div><span>ALERTS</span><h2>Benachrichtigungen</h2></div><Link href="/benachrichtigungen">Alle öffnen →</Link></div><div className="toggleList">{Object.entries(state.notifications).map(([k,v])=><label key={k}><span>{({messages:"Neue Nachrichten",tasks:"Neue/auslaufende Aufgaben",sessions:"Session bestätigt oder geändert",media:"Neue Medien",subscriptions:"Abo & Zahlung"} as Record<string,string>)[k]}</span><input type="checkbox" checked={v} onChange={e=>save({...state,notifications:{...state.notifications,[k]:e.target.checked}})}/></label>)}</div></section>}

    <section className="growthLinks"><Link href="/discover">Discover & Favoriten →</Link><Link href="/events">Events →</Link><Link href="/sicherheit">Sicherheitscenter →</Link></section>
  </main>
}
